In [18]:
from sentence_transformers import SentenceTransformer
import torch
# Load embedding model
device = "cuda" if torch.cuda.is_available() else "cpu"
model = SentenceTransformer("google/embeddinggemma-300m", device=device)
print(f"Using device: {device}")

Using device: cuda

In [19]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: c:\Users\HP\Desktop\Projects\NodeRAG\testing
The root directory is: c:\Users\HP\Desktop\Projects\NodeRAG

In [20]:
import pandas as pd
medical_questions = pd.read_parquet(f"{root_path}\GraphRAG-Benchmark\Datasets\Questions\medical_questions.parquet")
medical_questions = medical_questions[medical_questions.question_type == 'Complex Reasoning']
medical_questions

,id,source,question,answer,question_type,evidence,evidence_relations
1098,Medical-604c9d44,Medical,Why is a patient with fair skin and a history ...,Because both fair skin and immune suppression ...,Complex Reasoning,Fair skin is an independent risk factor for ba...,"Fair skin, light hair, and light eye color inc..."
1099,Medical-df366063,Medical,If a patient presents with a shiny bump on the...,"A medical and family history, physical and ski...",Complex Reasoning,A medical and family history should be perform...,BCC presents as shiny bumps; BCC most commonly...
1100,Medical-0a90f1f2,Medical,How does the management of recurrent basal cel...,Management of recurrence depends on risk and r...,Complex Reasoning,Management of recurrent basal cell carcinoma d...,Recurrence refers to BCC returning to the orig...
1101,Medical-831bb1e6,Medical,Which combination of risk factors should promp...,"A combination of older age, fair skin, and fam...",Complex Reasoning,Older age is a risk factor for basal cell carc...,Older age is associated with higher risk of BC...
1102,Medical-01e3a9ea,Medical,Why might a patient with a shiny bump and a hi...,Because radiation therapy is a risk factor for...,Complex Reasoning,A shiny bump can be a symptom of basal cell ca...,Radiation therapy is a risk factor for BCC; BC...
...,...,...,...,...,...,...,...
1602,Medical-1eda4787,Medical,Which patients with breast cancer should recei...,All patients of reproductive potential should ...,Complex Reasoning,All patients of reproductive potential should ...,Fertility preservation should be discussed bef...
1603,Medical-24f2e8ea,Medical,How does the presence of HER2 positivity alter...,HER2 positivity adds HER2-targeted therapy to ...,Complex Reasoning,HER2 positivity adds HER2-targeted therapy to ...,HER2-targeted therapy is used for HER2-positiv...
1604,Medical-d1a87cb4,Medical,What combination of clinical findings and diag...,Symptoms like bone pain or neurological sympto...,Complex Reasoning,Symptoms like bone pain or neurological sympto...,Metastatic breast cancer (MBC) is breast cance...
1605,Medical-311d66d6,Medical,Which risk factors should be evaluated in a pa...,"Family history, BRCA1/2 mutations, and assigne...",Complex Reasoning,Family history should be evaluated as a risk f...,"Risk factors include family history, BRCA muta..."
1606,Medical-ac117ebf,Medical,Why is a biopsy essential in both the diagnosi...,Biopsy is essential for definitive diagnosis a...,Complex Reasoning,A biopsy is essential for definitive diagnosis...,Biopsy is required for definitive diagnosis an...

In [21]:
question_ids = medical_questions['id'].to_list()
question_ids

['Medical-604c9d44',
 'Medical-df366063',
 'Medical-0a90f1f2',
 'Medical-831bb1e6',
 'Medical-01e3a9ea',
 'Medical-c69c2732',
 'Medical-f034d77d',
 'Medical-1eab8fa2',
 'Medical-14016ce3',
 'Medical-5e530443',
 'Medical-c8dd3e29',
 'Medical-a9a52704',
 'Medical-346b12e8',
 'Medical-8ff5dd5a',
 'Medical-322bb52d',
 'Medical-35fee661',
 'Medical-f473bcb0',
 'Medical-f3af6f24',
 'Medical-ade4b34a',
 'Medical-ade95016',
 'Medical-8435c9f6',
 'Medical-23e6b6df',
 'Medical-4744dfa7',
 'Medical-59ea36ca',
 'Medical-4124f00f',
 'Medical-ed26b623',
 'Medical-fbc9e7ec',
 'Medical-9a34e14c',
 'Medical-bfe2b31f',
 'Medical-b6fbf092',
 'Medical-55898188',
 'Medical-8b99b755',
 'Medical-e0f29bbd',
 'Medical-55f0c0e2',
 'Medical-8407a0ab',
 'Medical-7b4429ac',
 'Medical-6d12f4ff',
 'Medical-baed6d13',
 'Medical-eb7624ca',
 'Medical-0a6379ff',
 'Medical-462ecc23',
 'Medical-2782702e',
 'Medical-f978cb28',
 'Medical-4f5a8531',
 'Medical-db5aa2e3',
 'Medical-193a4b7f',
 'Medical-e9ac42f1',
 'Medical-78897235',
 'Medical-33494794',
 'Medical-a7826934',
 'Medical-50bafb57',
 'Medical-24373ebe',
 'Medical-9528082d',
 'Medical-8b16a7bd',
 'Medical-4fe06961',
 'Medical-41b1601a',
 'Medical-38fe5331',
 'Medical-4987de7f',
 'Medical-c2ead218',
 'Medical-4d01de98',
 'Medical-34a9155d',
 'Medical-b7e4be0e',
 'Medical-96bb3762',
 'Medical-7ea7ec68',
 'Medical-e7d1cd1c',
 'Medical-c7c59020',
 'Medical-ee49f3e8',
 'Medical-b77d8e3d',
 'Medical-6fb8996b',
 'Medical-edc3c6eb',
 'Medical-f3048835',
 'Medical-f79d978d',
 'Medical-47504b64',
 'Medical-328006b7',
 'Medical-659d7c0a',
 'Medical-689b17ad',
 'Medical-a7e62dce',
 'Medical-80912696',
 'Medical-aa1b8dbb',
 'Medical-d256aef2',
 'Medical-c09d2bcb',
 'Medical-5fdb115b',
 'Medical-9231a873',
 'Medical-ad0cc053',
 'Medical-5a6b98a7',
 'Medical-1c53b384',
 'Medical-0e2be889',
 'Medical-ff2105ab',
 'Medical-6a90b47e',
 'Medical-0d237b40',
 'Medical-cfab4b2d',
 'Medical-b2da7aee',
 'Medical-7b422282',
 'Medical-fc13ecfe',
 'Medical-3447851a',
 'Medical-97022167',
 'Medical-781a9787',
 'Medical-104b2f70',
 'Medical-e1ede6d6',
 'Medical-e8957bed',
 'Medical-38fc968c',
 'Medical-00ef7b5d',
 'Medical-ebfc4679',
 'Medical-f27c64c0',
 'Medical-5b17d14f',
 'Medical-bea3adf4',
 'Medical-99dd217e',
 'Medical-166bcaa7',
 'Medical-48cb097c',
 'Medical-a88065af',
 'Medical-c41cab28',
 'Medical-f00f6356',
 'Medical-c22fc609',
 'Medical-e7ebb96c',
 'Medical-c7bf38df',
 'Medical-833304f8',
 'Medical-efd5b238',
 'Medical-52ca0ffb',
 'Medical-16a39fa8',
 'Medical-a5d38351',
 'Medical-f57e3ab2',
 'Medical-7b682af7',
 'Medical-def9b488',
 'Medical-950b879f',
 'Medical-35afeb4b',
 'Medical-b9f39886',
 'Medical-6d56985a',
 'Medical-f9e22272',
 'Medical-efd1af00',
 'Medical-dc695a12',
 'Medical-34a70628',
 'Medical-5e3016f9',
 'Medical-e0c754c6',
 'Medical-6ac9b753',
 'Medical-23080670',
 'Medical-bd7c7e1a',
 'Medical-92ed141f',
 'Medical-6428d1f1',
 'Medical-04e9f25b',
 'Medical-213bbcca',
 'Medical-e0a5fcc5',
 'Medical-423d4257',
 'Medical-68ea8206',
 'Medical-e2ac8ec4',
 'Medical-413d4c7e',
 'Medical-f63520dd',
 'Medical-8307a348',
 'Medical-86e095c3',
 'Medical-02d254bc',
 'Medical-83eb6b6b',
 'Medical-df78005a',
 'Medical-f8e45373',
 'Medical-b503f3f3',
 'Medical-705f9e89',
 'Medical-8779d729',
 'Medical-f7300f3c',
 'Medical-c31057de',
 'Medical-45173331',
 'Medical-1930c305',
 'Medical-9d34bcac',
 'Medical-68694b91',
 'Medical-9bc8aaa1',
 'Medical-b2a64d4a',
 'Medical-4b359d87',
 'Medical-5459ea22',
 'Medical-f25adcc2',
 'Medical-904e0a11',
 'Medical-3c536762',
 'Medical-aacc98ed',
 'Medical-7bf81d77',
 'Medical-6e39cbe0',
 'Medical-41284331',
 'Medical-f078c897',
 'Medical-7c1c087a',
 'Medical-787b9c0b',
 'Medical-a0c1c9cd',
 'Medical-c5b8734d',
 'Medical-56f4cb0b',
 'Medical-7f3beb74',
 'Medical-2d14639d',
 'Medical-1e1b5f1d',
 'Medical-a660735d',
 'Medical-4a4eaab8',
 'Medical-37f18801',
 'Medical-d7e8bc97',
 'Medical-6a5c89f3',
 'Medical-c76b58b2',
 'Medical-fb234ffb',
 'Medical-0030eab4',
 'Medical-f9bc1472',
 'Medical-3aa8a2c6',
 'Medical-96508468',
 'Medical-98bb0bbc',
 'Medical-5581adb2',
 'Medical-31580ac0',
 'Medical-cfc21569',
 'Medical-443e3d36',
 'Medical-e9ef7d6f',
 'Medical-c2af5dd7',
 'Medical-83ff7511',
 'Medical-5a2c0504',
 'Medical-38a8b852',
 'Medical-0b5acb42',
 'Medical-535c413f',
 'Medical-c6a7964c',
 'Medical-803f66d8',
 'Medical-819d9c6c',
 'Medical-ac781c3a',
 'Medical-0955a900',
 'Medical-18be1c24',
 'Medical-09eac393',
 'Medical-3f8a738d',
 'Medical-03451b65',
 'Medical-f4972c91',
 'Medical-a0cd1d28',
 'Medical-2f70ddcb',
 'Medical-6e99ce81',
 'Medical-b94e5d8e',
 'Medical-32fce5f0',
 'Medical-e1deaedc',
 'Medical-ee644399',
 'Medical-072545c5',
 'Medical-0e57f27f',
 'Medical-c58fae3b',
 'Medical-66e7fe35',
 'Medical-47b62614',
 'Medical-06055fa9',
 'Medical-81c95a46',
 'Medical-fe7f2575',
 'Medical-ce635798',
 'Medical-b2b43c1e',
 'Medical-e6db1c4b',
 'Medical-14d39f0c',
 'Medical-bce86fcf',
 'Medical-a6155d9a',
 'Medical-9b3c8ac0',
 'Medical-4aed3e10',
 'Medical-641dcaf5',
 'Medical-333a4a3b',
 'Medical-54cc91bf',
 'Medical-ee09c8e9',
 'Medical-27c72004',
 'Medical-fe83d01e',
 'Medical-69bd1f37',
 'Medical-70db1204',
 'Medical-b016ff7a',
 'Medical-7dd235f1',
 'Medical-5adcec8a',
 'Medical-25d1d605',
 'Medical-2cc4ff58',
 'Medical-48843076',
 'Medical-aa9a54c8',
 'Medical-ec4712e3',
 'Medical-299b8b83',
 'Medical-2350fb33',
 'Medical-984c0f56',
 'Medical-01abc791',
 'Medical-7faeddee',
 'Medical-ef429fbb',
 'Medical-370cff35',
 'Medical-3e87c7a1',
 'Medical-84ec68f0',
 'Medical-2157ec85',
 'Medical-56e2a338',
 'Medical-33af9785',
 'Medical-7fba506d',
 'Medical-032223d5',
 'Medical-d42f24b5',
 'Medical-c4772f49',
 'Medical-cb781b83',
 'Medical-6cb18929',
 'Medical-569780c4',
 'Medical-32b9ef93',
 'Medical-6f0e62e5',
 'Medical-732c4e13',
 'Medical-889e2c6a',
 'Medical-68c30458',
 'Medical-3a5fb7b0',
 'Medical-4191d4b2',
 'Medical-43a4d872',
 'Medical-9386f24f',
 'Medical-91742d51',
 'Medical-c6b862bd',
 'Medical-39012a36',
 'Medical-ca3e2437',
 'Medical-ec84ae56',
 'Medical-890965f6',
 'Medical-2a61ebd2',
 'Medical-0a8d750c',
 'Medical-f6a94128',
 'Medical-4e39d9d5',
 'Medical-57f0c93d',
 'Medical-ddde0e24',
 'Medical-c57bf64d',
 'Medical-640a315c',
 'Medical-669af50b',
 'Medical-1ab31cd8',
 'Medical-575e6d7f',
 'Medical-ee302181',
 'Medical-54a3a465',
 'Medical-8f1032c7',
 'Medical-ffffe4b8',
 'Medical-2521e4dd',
 'Medical-884a8392',
 'Medical-e851fe04',
 'Medical-6e8f1b95',
 'Medical-18fc35e5',
 'Medical-eb042e58',
 'Medical-6bed629f',
 'Medical-0be2176d',
 'Medical-45847608',
 'Medical-4e5d3831',
 'Medical-d7765001',
 'Medical-e2bcebf4',
 'Medical-22b8a5ee',
 'Medical-eab49131',
 'Medical-223def84',
 'Medical-48e987ed',
 'Medical-c92bbd26',
 'Medical-2ebcf55d',
 'Medical-a7fb4f11',
 'Medical-ce7076ea',
 'Medical-6108fa72',
 'Medical-56131016',
 'Medical-1e7500e4',
 'Medical-29a8ae2e',
 'Medical-3776fc3d',
 'Medical-836e7db0',
 'Medical-1852bc75',
 'Medical-8ac49b5b',
 'Medical-cf2fbd21',
 'Medical-30e7caf0',
 'Medical-ab708cf8',
 'Medical-321f2f6d',
 'Medical-95bdfdba',
 'Medical-1892185a',
 'Medical-ade34649',
 'Medical-cd4d3dd1',
 'Medical-6624a28a',
 'Medical-60acb9ee',
 'Medical-ac502742',
 'Medical-6e4da4de',
 'Medical-b6f1658b',
 'Medical-a0a1a141',
 'Medical-6e3e48fa',
 'Medical-2529e505',
 'Medical-68e55e0e',
 'Medical-8d55a40b',
 'Medical-8233f77f',
 'Medical-bc622c63',
 'Medical-de3d6946',
 'Medical-5f54bb84',
 'Medical-618ab93c',
 'Medical-bb678310',
 'Medical-58981bbb',
 'Medical-63b4b70c',
 'Medical-d163acf5',
 'Medical-2a24f6a2',
 'Medical-417cbcfd',
 'Medical-6a1c421a',
 'Medical-4777cfbb',
 'Medical-88e1fb4a',
 'Medical-2ca88e8f',
 'Medical-213847bd',
 'Medical-1a56336a',
 'Medical-a4ac550d',
 'Medical-4d6219bc',
 'Medical-ef073c61',
 'Medical-99964376',
 'Medical-cdce534a',
 'Medical-1f7241a3',
 'Medical-d186c439',
 'Medical-222ee61b',
 'Medical-c650bba8',
 'Medical-50fe4cfa',
 'Medical-ac73c113',
 'Medical-f7ce6257',
 'Medical-136a5739',
 'Medical-aaefb0f2',
 'Medical-a5435dbc',
 'Medical-e8163237',
 'Medical-af6105a0',
 'Medical-c58dca0f',
 'Medical-f5089b0a',
 'Medical-a73aa030',
 'Medical-fad3190e',
 'Medical-2e2c9c8e',
 'Medical-9675683c',
 'Medical-26ced7a1',
 'Medical-a6968a78',
 'Medical-91c35427',
 'Medical-da2b7d6f',
 'Medical-27edd702',
 'Medical-ac86bfad',
 'Medical-d1c9cdcd',
 'Medical-0bd26353',
 'Medical-025c325c',
 'Medical-79d13dd8',
 'Medical-a0699e9e',
 'Medical-a7a91e43',
 'Medical-b200a90c',
 'Medical-2a5688d0',
 'Medical-e54f3250',
 'Medical-18263083',
 'Medical-648df362',
 'Medical-97e7a1d0',
 'Medical-a56d528c',
 'Medical-99713759',
 'Medical-daeae948',
 'Medical-d2458aa7',
 'Medical-ed5085d7',
 'Medical-74b73ed7',
 'Medical-bb361e83',
 'Medical-6b3f89bd',
 'Medical-a5f2e7a9',
 'Medical-4ff142d9',
 'Medical-5504201a',
 'Medical-6d335c18',
 'Medical-b272ce63',
 'Medical-32861246',
 'Medical-219da1ba',
 'Medical-ec0be6f4',
 'Medical-3964e4de',
 'Medical-441c763b',
 'Medical-9626892c',
 'Medical-402f416c',
 'Medical-59890a0c',
 'Medical-fd4cca6e',
 'Medical-9499de40',
 'Medical-bcfc4592',
 'Medical-fd151825',
 'Medical-27281f31',
 'Medical-95283550',
 'Medical-fdd40f83',
 'Medical-3d54d9e7',
 'Medical-a3c6c911',
 'Medical-64f219fe',
 'Medical-99cbd976',
 'Medical-e1ef9e9b',
 'Medical-1024ca84',
 'Medical-40446029',
 'Medical-2b2dd1fb',
 'Medical-04fc1c61',
 'Medical-594504cc',
 'Medical-3d9e3424',
 'Medical-141fd876',
 'Medical-5422875d',
 'Medical-82f4c628',
 'Medical-2148e062',
 'Medical-2be4d7f3',
 'Medical-3a5671fc',
 'Medical-42d7ac7c',
 'Medical-4f7fc60b',
 'Medical-f2800f11',
 'Medical-833eac1d',
 'Medical-25c17c3d',
 'Medical-17015c75',
 'Medical-fa092b30',
 'Medical-c218fffa',
 'Medical-056e1e60',
 'Medical-bb794987',
 'Medical-aba4e30c',
 'Medical-0103d518',
 'Medical-ad078f77',
 'Medical-b914d234',
 'Medical-b3fece20',
 'Medical-0093e2ec',
 'Medical-65f00413',
 'Medical-cfdb85ba',
 'Medical-727f425f',
 'Medical-9b9b7f4a',
 'Medical-72cfd9c6',
 'Medical-e9900b5c',
 'Medical-3bea99a2',
 'Medical-0125ebb1',
 'Medical-33e5776d',
 'Medical-b0ec1abf',
 'Medical-5c6a1008',
 'Medical-2e171c34',
 'Medical-a9db9ed9',
 'Medical-015f2cf7',
 'Medical-1a7ab06f',
 'Medical-5456c556',
 'Medical-d3dfaf75',
 'Medical-e3da3cd7',
 'Medical-9db4f113',
 'Medical-395b9708',
 'Medical-7718481e',
 'Medical-8e0c15db',
 'Medical-6e464eb2',
 'Medical-15b033b6',
 'Medical-5e710a7f',
 'Medical-c0103315',
 'Medical-2045d4e4',
 'Medical-ef8fe744',
 'Medical-8ff4d088',
 'Medical-020cc551',
 'Medical-1c34ae24',
 'Medical-e99acf57',
 'Medical-a13a1285',
 'Medical-647b438f',
 'Medical-6bd5b75d',
 'Medical-8488f954',
 'Medical-f5688b0c',
 'Medical-1eda4787',
 'Medical-24f2e8ea',
 'Medical-d1a87cb4',
 'Medical-311d66d6',
 'Medical-ac117ebf']

In [22]:
import sys
sys.path.append(root_path)
from graphs.Node import Node
from answering.get_context import get_context
from answering.answer_prompt import answer_prompt

In [23]:
#Load Data
import pickle
import json
import faiss
import pandas as pd
import numpy as np
#Graph - Node dict
with open(f"{root_path}/graphs/data/graphs/G6_entity_and_chunk_resolution_graph.pkl", "rb") as f:
    medical_graph = pickle.load(f)

#Embeddings
hnsw = faiss.read_index(f"{root_path}/graphs/data/embedding/medical_index.faiss")
with open(f"{root_path}/graphs/data/embedding/medical_ids.json", "r") as f:
    medical_embedding_ids = json.load(f)
num_vectors = hnsw.ntotal
dimension = hnsw.d
embeddings = np.zeros((num_vectors, dimension), dtype='float32')
for i in range(num_vectors):
    embeddings[i] = hnsw.reconstruct(i)

#Entities
with open(f"{root_path}/graphs/data/nodes/entity/medical_entities.pkl", "rb") as f:
    medical_entities = pickle.load(f)
medical_overview = pd.read_parquet(f"{root_path}/graphs/data/nodes/community/medical_communities_overview.parquet")

In [24]:
#LLM api call
from google import genai
with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()

def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text
    )
    return response

In [25]:
graph_context = {
    'graph': medical_graph,
    'entities': medical_entities,
    'overview': medical_overview
}

embedding_context = {
    'model': model,
    'index': hnsw,
    'ids': medical_embedding_ids,
}

In [26]:
#Case 1: No graph reasoning

try:
    normal_rag_answer = pd.read_parquet("data/normal_rag_answer.parquet")
except:
    normal_rag_answer = medical_questions.copy(deep=True)
    normal_rag_answer[["LLM_answer", "LLM_context", "LLM_tokens"]] = None

normal_rag_answer

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
1098,Medical-604c9d44,Medical,Why is a patient with fair skin and a history ...,Because both fair skin and immune suppression ...,Complex Reasoning,Fair skin is an independent risk factor for ba...,"Fair skin, light hair, and light eye color inc...",None,None,None
1099,Medical-df366063,Medical,If a patient presents with a shiny bump on the...,"A medical and family history, physical and ski...",Complex Reasoning,A medical and family history should be perform...,BCC presents as shiny bumps; BCC most commonly...,None,None,None
1100,Medical-0a90f1f2,Medical,How does the management of recurrent basal cel...,Management of recurrence depends on risk and r...,Complex Reasoning,Management of recurrent basal cell carcinoma d...,Recurrence refers to BCC returning to the orig...,None,None,None
1101,Medical-831bb1e6,Medical,Which combination of risk factors should promp...,"A combination of older age, fair skin, and fam...",Complex Reasoning,Older age is a risk factor for basal cell carc...,Older age is associated with higher risk of BC...,None,None,None
1102,Medical-01e3a9ea,Medical,Why might a patient with a shiny bump and a hi...,Because radiation therapy is a risk factor for...,Complex Reasoning,A shiny bump can be a symptom of basal cell ca...,Radiation therapy is a risk factor for BCC; BC...,None,None,None
...,...,...,...,...,...,...,...,...,...,...
1602,Medical-1eda4787,Medical,Which patients with breast cancer should recei...,All patients of reproductive potential should ...,Complex Reasoning,All patients of reproductive potential should ...,Fertility preservation should be discussed bef...,None,None,None
1603,Medical-24f2e8ea,Medical,How does the presence of HER2 positivity alter...,HER2 positivity adds HER2-targeted therapy to ...,Complex Reasoning,HER2 positivity adds HER2-targeted therapy to ...,HER2-targeted therapy is used for HER2-positiv...,None,None,None
1604,Medical-d1a87cb4,Medical,What combination of clinical findings and diag...,Symptoms like bone pain or neurological sympto...,Complex Reasoning,Symptoms like bone pain or neurological sympto...,Metastatic breast cancer (MBC) is breast cance...,None,None,None
1605,Medical-311d66d6,Medical,Which risk factors should be evaluated in a pa...,"Family history, BRCA1/2 mutations, and assigne...",Complex Reasoning,Family history should be evaluated as a risk f...,"Risk factors include family history, BRCA muta...",None,None,None
1606,Medical-ac117ebf,Medical,Why is a biopsy essential in both the diagnosi...,Biopsy is essential for definitive diagnosis a...,Complex Reasoning,A biopsy is essential for definitive diagnosis...,Biopsy is required for definitive diagnosis an...,None,None,None

In [27]:
LLM_answer_1 = (
    normal_rag_answer.loc[normal_rag_answer[["LLM_answer", "LLM_context", "LLM_tokens"]].notna().all(axis=1) &
        (normal_rag_answer[["LLM_answer", "LLM_context", "LLM_tokens"]] != "").all(axis=1)
        ].set_index("id")[["LLM_answer", "LLM_context", "LLM_tokens"]].to_dict(orient="index"))

LLM_answer_1

{}

In [28]:
#Context setup
ppr_context = {
    'k_ppr': 0,
    'alpha': 0.5,
    't':5
}
query_context = {
    'question': None,
    'k_embedding': 8,
    'ppr': ppr_context
}

In [ ]:
from tqdm import tqdm
import time
sep = "\n\n" + "-"*100 + "\n\n"
MAX_RETRIES = 20
SLEEP_SEC = 30

def get_answers_1():
    for qid in tqdm(question_ids):
        if qid in LLM_answer_1:
            continue
        row = medical_questions.loc[medical_questions["id"] == qid].iloc[0]
        question = row["question"]
        query_context["question"] = question
        for attempt in range(1, MAX_RETRIES + 1):
            try:
                context = get_context(query_context,graph_context,embedding_context,API_KEY,debug=False)
                full_context = sep.join(context.values())
                prompt = answer_prompt(full_context, question)
                response = call_gemini(prompt)
                answer = response.text
                usage = response.usage_metadata
                #log
                LLM_answer_1[qid] = {
                    "LLM_answer": answer,
                    "LLM_context": full_context,
                    "LLM_tokens": usage.total_token_count,
                }
                break

            except Exception as e:
                code = e.error.code if hasattr(e, "error") else e
                print(f"[ERROR] qid={qid} failed after {attempt} retries: {code}")
                if attempt == MAX_RETRIES:
                    return
                time.sleep(SLEEP_SEC * attempt)  #backoff

get_answers_1()

  0%|          | 0/509 [00:05<?, ?it/s]

In [30]:
LLM_answer_1

{'Medical-604c9d44': {'LLM_answer': 'A patient with fair skin is at a higher risk for basal cell carcinoma because their skin has less melanin to filter harmful UV rays. Additionally, individuals with a history of organ transplant experience immune suppression, which further increases their risk of developing basal cell carcinoma.',
  'LLM_context': "Here are distinct categories of high-level information extracted from the text cluster, providing a well-rounded overview:\n\n---\n\n### 1. Common Skin Cancers: Prevalence and Curability\n\n**Description:** This cluster predominantly addresses Basal Cell Carcinoma (BCC) and Squamous Cell Carcinoma (CSCC), identifying them as the most common types of skin cancer, collectively known as nonmelanoma skin cancers. BCC is the most prevalent, with approximately 3 million annual diagnoses in the U.S., while CSCC is the second most common. Both are generally highly treatable and curable, especially when detected early, owing to their less aggressive nature compared to melanoma and their infrequent metastasis.\n\n### 2. Etiology and Cellular Basis of Skin Cancers\n\n**Description:** Most skin cancers originate in the Epidermis, the skin's outermost layer. Basal Cell Carcinoma arises when basal cells (lower epidermis) grow uncontrollably, while Squamous Cell Carcinoma forms from abnormal squamous cells (upper epidermis). The primary cause for both is exposure to ultraviolet (UV) radiation from sun or tanning beds, which damages cellular DNA. Risk factors include lighter skin/hair/eyes (less melanin protection), increasing age, personal/family history of skin cancer, prior radiation therapy, and immune suppression.\n\n### 3. The Skin as a Multifaceted Organ and Cancer Origin\n\n**Description:** The skin, the human body's largest organ, acts as a vital barrier against external threats, regulates body temperature, and provides sensory input. It comprises three layers: the Epidermis (waterproof barrier, melanin production, site of most skin cancers), Dermis (connective tissue, vessels, glands), and Hypodermis (fat and connective tissue). The Epidermis specifically houses three main cell types—Squamous cells, Basal cells, and Melanocytes—each playing a critical role, but also serving as the specific cellular origins for the major types of skin cancers.\n\n### 4. Varied Manifestations and Crucial Early Detection\n\n**Description:** Skin cancers present diverse appearances, making vigilant self-monitoring and professional examination essential. Basal Cell Carcinoma can manifest as flat, pale/yellow scar-like areas, itchy red patches, small shiny pink/red bumps (potentially with darker flecks), or non-healing, bleeding sores. In darker skin, it may appear as a brown or glossy black bump with a rolled border, mimicking a mole. Squamous Cell Carcinoma often appears as scaly or rough patches. Early detection through monitoring new, changing, bleeding, or unusual growths, followed by diagnostic testing (health history, examination, skin biopsy, imaging), is paramount for effective treatment and curability.\n\n### 5. Comprehensive Treatment Approaches for Skin Cancers\n\n**Description:** Treatment for skin cancers is highly individualized and employs a wide range of modalities. Surgery is the most common and often definitive treatment, including techniques like standard excision, Mohs surgery, curettage, and electrodesiccation. For earlier or pre-cancerous lesions (e.g., Actinic Keratosis, Bowen’s disease), superficial treatments like cryotherapy (freezing), topical therapies (e.g., 5-fluorouracil, imiquimod, tirbanibulin, calcipotriene), and photodynamic therapy are utilized. Radiation therapy serves as an alternative for non-surgical candidates or post-operative adjunct. For advanced or recurrent cases, systemic therapies such as targeted therapies, immunotherapy (PD-1 inhibitors), and chemotherapy are employed, with clinical trials offering access to novel treatments.\n\n### 6. Pre-Cancerous Indicators and Unique Skin Cancer Presentations\n\n**Description:** Actinic Keratosis, characterized by scaly or rough skin, is a significant pre-cancerous lesion caused by prolonged sun exposure that increases the risk of developing Squamous Cell Carcinoma (CSCC). Its varied appearance and location on sun-exposed areas necessitate medical attention. Another unique and challenging presentation is Marjolin’s ulcer, a severe form of CSCC that arises in chronic, non-healing wounds, scars, or burns, requiring specialized treatment considerations.\n\n### 7. Long-Term Surveillance and Prevention Strategies\n\n**Description:** Following successful treatment for skin cancer, long-term vigilance is critical. Patients face an elevated risk of both recurrence (cancer returning or spreading) and developing new skin cancers. Regular, comprehensive follow-up skin exams by a doctor (including lymph node checks), typically at least annually and more frequently in the initial years, are crucial. Prevention efforts, particularly minimizing UV exposure from the sun and tanning beds, are emphasized as key strategies to reduce future risk.\n\n### 8. Squamous Cell Carcinoma Beyond the Skin: A Systemic Concern\n\n**Description:** While prominent on the skin, squamous cells are ubiquitous, lining various internal organs, and can give rise to Squamous Cell Carcinoma (SCC) in those locations. This includes the lungs (as a subtype of Non-Small Cell Lung Cancer), the cervix, and the anal canal. The text highlights that SCC originating in these internal organs behaves and is treated differently from cutaneous (skin-based) SCC, underscoring the broader systemic impact and diverse manifestations of this cancer type.\n\n### 9. Specialized Oncology Care and Genetic Predisposition\n\n**Description:** Individuals with genetic syndromes (e.g., Xeroderma pigmentosum, Recessive Dystrophic Epidermolysis Bullosa) or a family history indicating a genetic risk for skin cancer require specialized care. Cancer Centers offer comprehensive prevention, diagnosis, and treatment for conditions like CSCC, often complemented by counseling from cancer genetics experts (genetic counselors, medical geneticists, oncologists). These centers provide tailored approaches, advanced diagnostic tools (e.g., imaging, specialized biopsies), and access to multidisciplinary teams to manage complex cases and genetic predispositions.\n\n----------------------------------------------------------------------------------------------------\n\nCauses and risk factors Basal cell skin cancer is caused by exposure to UV radiation from the sun or other sources like tanning beds. UV radiation can harm the DNA inside basal skin cells. DNA controls how cells grow and function. If the DNA inside cells becomes damaged, the cells can become abnormal and grow out of control. You’re more likely to have basal cell skin cancer if you have certain risk factors. A risk factor increases the chance of developing cancer. Fair skin, red or blond hair, or light eye color – People with lighter-colored skin are at a higher risk of developing skin cancer because melanin (skin pigment) filters out the sun's harmful UV rays. Age – Risk increases with age because sun exposure builds up over time. But skin cancer is becoming more common in younger people. History of skin cancer – If you or someone in your family has had skin cancer, you’re more likely to develop any type of skin cancer. Radiation therapy – Radiation treatment for other conditions, especially at a young age, can cause skin cancer. Immune suppression – People with weakened immune systems from organ transplants or autoimmune diseases are at higher risk for basal cell skin cancer. How is basal cell skin cancer treated? Basal cell skin cancer is highly treatable and curable. Catching it and treating it early is key. Surgery is the most common treatment for basal cell skin cancer. In some cases, radiation therapy or systemic therapy might be used to treat it. Following your treatment, you will have full skin exams with your doctor at least once a year. Between these periods, prevention is important. See Chapter 4: Treatment by risk and recurrence for more information. Recurrence is when basal cell skin cancer returns to the area where it was originally found, or it has metastasized (spread) to the lymph nodes or to distant parts of the body. But there are several options for how to treat it. Read more about how your cancer is treated in Chapter 3: Types of treatment and Chapter 4: Treatment by risk and recurrence. What can you do to get the best care? Advocate for yourself. You have an important role to play in your care. In fact, you’re more likely to get the care you want by asking questions and making shared decisions with your care team.\n\n----------------------------------------------------------------------------------------------------\n\nSunlight and outdoor tanning are primary causes of most squamous cell skin cancers, resulting from excessive sun exposure over many years. Individuals who sunburn easily, those with light skin, hair, and eyes who have had frequent sun exposure, and people working outdoors face the highest risk. Long-term sun exposure, frequent tanning, and sunburns collectively contribute to the development of this cancer.\n\n----------------------------------------------------------------------------------------------------\n\nThe deeper a tumor has invaded into the skin, the higher the risk that the cancer will return after treatment or spread to distant body sites.\n\n----------------------------------------------------------------------------------------------------\n\nSeveral factors indicate a higher risk for cancer, its recurrence, or spread. These include the presence of fibrous or connective tissue within the tumor, the depth of tumor invasion into the skin, and the presence of cancer cells in lymph or blood vessels (known as lymphovascular invasion). Additionally, a weakened immune system due to conditions like long-term corticosteroid use, HIV/AIDS, or organ transplant also contributes to this risk.\n\n----------------------------------------------------------------------------------------------------\n\nBasal cell skin cancer is caused by exposure to UV radiation from the sun or tanning beds, which damages the DNA within basal skin cells, leading to abnormal and uncontrolled cell growth. Several risk factors increase the likelihood of developing this cancer, including fair skin, red or blond hair, or light eye color, as lighter skin has less melanin to filter harmful UV rays. Other risk factors are increasing age due to cumulative sun exposure, a personal or family history of skin cancer, prior radiation therapy (especially at a young age), and immune suppression resulting from conditions like organ transplants or autoimmune diseases.\n\n----------------------------------------------------------------------------------------------------\n\nA weakened immune system, which impairs the body's ability to fight off viruses, bacteria, and fungi, increases the risk of squamous cell skin cancer. This weakening can result from organ transplantation, where immunosuppressants are taken, or from health conditions like Lymphoma (cancer of the lymph nodes), Chronic lymphocytic leukemia (cancer of white blood cells in bone marrow), Human immunodeficiency virus (HIV), or AIDS. Individuals with a weakened immune system should undergo regular skin cancer screening.\n\n----------------------------------------------------------------------------------------------------\n\nBasal cell skin cancer can affect anyone but is most common in individuals with lighter skin, hair, or eyes. In lighter skin, its lesions can manifest as flat, pale, or yellow areas resembling a scar; itchy red patches; small, pink or red, shiny bumps potentially containing blue, brown, or black areas; or open sores that do not heal, may bleed, or recur. In darker (brown and black) skin, basal cell skin cancer can appear as a brown or glossy black bump with a rolled border, which might be mistaken for a normal mole. It is important to monitor for any new, changing, bleeding, or unusual skin growths, as skin cancer is more curable when detected early.",
  'LLM_tokens': 2727}}

In [31]:
llm_df_1 = (
    pd.DataFrame.from_dict(LLM_answer_1, orient="index")
      .reset_index()
      .rename(columns={"index": "id"})
)
llm_df_1

,id,LLM_answer,LLM_context,LLM_tokens
0,Medical-604c9d44,A patient with fair skin is at a higher risk f...,Here are distinct categories of high-level inf...,2727

In [32]:
print("min:", llm_df_1["LLM_tokens"].min())
print("max:", llm_df_1["LLM_tokens"].max())
print("avg:", llm_df_1["LLM_tokens"].mean())
print("sum:", llm_df_1["LLM_tokens"].sum())

min: 2727
max: 2727
avg: 2727.0
sum: 2727

In [33]:
normal_rag_answer = medical_questions.merge(
    llm_df_1,
    on="id",
    how="left"
)
normal_rag_answer

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
0,Medical-604c9d44,Medical,Why is a patient with fair skin and a history ...,Because both fair skin and immune suppression ...,Complex Reasoning,Fair skin is an independent risk factor for ba...,"Fair skin, light hair, and light eye color inc...",A patient with fair skin is at a higher risk f...,Here are distinct categories of high-level inf...,2727.0
1,Medical-df366063,Medical,If a patient presents with a shiny bump on the...,"A medical and family history, physical and ski...",Complex Reasoning,A medical and family history should be perform...,BCC presents as shiny bumps; BCC most commonly...,NaN,NaN,NaN
2,Medical-0a90f1f2,Medical,How does the management of recurrent basal cel...,Management of recurrence depends on risk and r...,Complex Reasoning,Management of recurrent basal cell carcinoma d...,Recurrence refers to BCC returning to the orig...,NaN,NaN,NaN
3,Medical-831bb1e6,Medical,Which combination of risk factors should promp...,"A combination of older age, fair skin, and fam...",Complex Reasoning,Older age is a risk factor for basal cell carc...,Older age is associated with higher risk of BC...,NaN,NaN,NaN
4,Medical-01e3a9ea,Medical,Why might a patient with a shiny bump and a hi...,Because radiation therapy is a risk factor for...,Complex Reasoning,A shiny bump can be a symptom of basal cell ca...,Radiation therapy is a risk factor for BCC; BC...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
504,Medical-1eda4787,Medical,Which patients with breast cancer should recei...,All patients of reproductive potential should ...,Complex Reasoning,All patients of reproductive potential should ...,Fertility preservation should be discussed bef...,NaN,NaN,NaN
505,Medical-24f2e8ea,Medical,How does the presence of HER2 positivity alter...,HER2 positivity adds HER2-targeted therapy to ...,Complex Reasoning,HER2 positivity adds HER2-targeted therapy to ...,HER2-targeted therapy is used for HER2-positiv...,NaN,NaN,NaN
506,Medical-d1a87cb4,Medical,What combination of clinical findings and diag...,Symptoms like bone pain or neurological sympto...,Complex Reasoning,Symptoms like bone pain or neurological sympto...,Metastatic breast cancer (MBC) is breast cance...,NaN,NaN,NaN
507,Medical-311d66d6,Medical,Which risk factors should be evaluated in a pa...,"Family history, BRCA1/2 mutations, and assigne...",Complex Reasoning,Family history should be evaluated as a risk f...,"Risk factors include family history, BRCA muta...",NaN,NaN,NaN
508,Medical-ac117ebf,Medical,Why is a biopsy essential in both the diagnosi...,Biopsy is essential for definitive diagnosis a...,Complex Reasoning,A biopsy is essential for definitive diagnosis...,Biopsy is required for definitive diagnosis an...,NaN,NaN,NaN

In [34]:
normal_rag_answer.to_parquet("data/normal_rag_answer.parquet")
normal_rag_answer_loaded = pd.read_parquet("data/normal_rag_answer.parquet")
normal_rag_answer_loaded

,id,source,question,answer,question_type,evidence,evidence_relations,LLM_answer,LLM_context,LLM_tokens
0,Medical-604c9d44,Medical,Why is a patient with fair skin and a history ...,Because both fair skin and immune suppression ...,Complex Reasoning,Fair skin is an independent risk factor for ba...,"Fair skin, light hair, and light eye color inc...",A patient with fair skin is at a higher risk f...,Here are distinct categories of high-level inf...,2727.0
1,Medical-df366063,Medical,If a patient presents with a shiny bump on the...,"A medical and family history, physical and ski...",Complex Reasoning,A medical and family history should be perform...,BCC presents as shiny bumps; BCC most commonly...,None,None,NaN
2,Medical-0a90f1f2,Medical,How does the management of recurrent basal cel...,Management of recurrence depends on risk and r...,Complex Reasoning,Management of recurrent basal cell carcinoma d...,Recurrence refers to BCC returning to the orig...,None,None,NaN
3,Medical-831bb1e6,Medical,Which combination of risk factors should promp...,"A combination of older age, fair skin, and fam...",Complex Reasoning,Older age is a risk factor for basal cell carc...,Older age is associated with higher risk of BC...,None,None,NaN
4,Medical-01e3a9ea,Medical,Why might a patient with a shiny bump and a hi...,Because radiation therapy is a risk factor for...,Complex Reasoning,A shiny bump can be a symptom of basal cell ca...,Radiation therapy is a risk factor for BCC; BC...,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...
504,Medical-1eda4787,Medical,Which patients with breast cancer should recei...,All patients of reproductive potential should ...,Complex Reasoning,All patients of reproductive potential should ...,Fertility preservation should be discussed bef...,None,None,NaN
505,Medical-24f2e8ea,Medical,How does the presence of HER2 positivity alter...,HER2 positivity adds HER2-targeted therapy to ...,Complex Reasoning,HER2 positivity adds HER2-targeted therapy to ...,HER2-targeted therapy is used for HER2-positiv...,None,None,NaN
506,Medical-d1a87cb4,Medical,What combination of clinical findings and diag...,Symptoms like bone pain or neurological sympto...,Complex Reasoning,Symptoms like bone pain or neurological sympto...,Metastatic breast cancer (MBC) is breast cance...,None,None,NaN
507,Medical-311d66d6,Medical,Which risk factors should be evaluated in a pa...,"Family history, BRCA1/2 mutations, and assigne...",Complex Reasoning,Family history should be evaluated as a risk f...,"Risk factors include family history, BRCA muta...",None,None,NaN
508,Medical-ac117ebf,Medical,Why is a biopsy essential in both the diagnosi...,Biopsy is essential for definitive diagnosis a...,Complex Reasoning,A biopsy is essential for definitive diagnosis...,Biopsy is required for definitive diagnosis an...,None,None,NaN