# Notebook 5: Community Detection and Aggregation

This notebook processes the attribute-enriched graph **G2** to detect structural communities using the **Leiden algorithm**.

For each community, the LLM is invoked to generate a **community summary** using all semantic units within that community.  
If a community contains only one semantic unit, summarization is skipped.  
These summaries form the content for **High-level Element (H) nodes**.

From each community summary, an additional LLM call extracts **keywords** and **titles**.  
These results serve as the content for **High-level Overview (O) nodes**.

The resulting communities are also saved for future processing.

In [1]:
import os
dir_path = os.getcwd()
print("The directory of this script is:", dir_path)
root_path = os.path.dirname(dir_path)
print("The root directory is:", root_path)

The directory of this script is: c:\Users\HP\Desktop\Projects\NodeRAG\graphs
The root directory is: c:\Users\HP\Desktop\Projects\NodeRAG

In [2]:
import sys
sys.path.append(root_path)
from graphs.Node import Node

In [3]:
import pickle
with open(f"{root_path}/graphs/data/graphs/G2_medical_attribute_enriched_graph.pkl", "rb") as f:
    medical_g2 = pickle.load(f)

In [4]:
import igraph as ig
from leidenalg import find_partition, ModularityVertexPartition
from collections import defaultdict

def leiden_community_detection(node_dict):
    id_to_idx = {nid: i for i, nid in enumerate(node_dict.keys())}
    idx_to_id = {v: k for k, v in id_to_idx.items()}

    edge_weights = defaultdict(float)
    for nid, node in node_dict.items():
        for neighbor, weight in node.edges.items():
            a, b = id_to_idx[nid], id_to_idx[neighbor]
            if a < b:
                edge_weights[(a, b)] += weight

    edges = list(edge_weights.keys())
    weights = list(edge_weights.values())

    g = ig.Graph(n=len(node_dict), edges=edges, directed=False)
    g.es["weight"] = weights

    partition = find_partition(g, ModularityVertexPartition, weights="weight")
    membership = partition.membership
    communities = {idx_to_id[i]: membership[i] for i in range(len(node_dict))}
    return communities

In [5]:
from collections import Counter
medical_communities = leiden_community_detection(medical_g2)
medical_communities_counts = Counter(medical_communities.values())
s1 = 0
for val in medical_communities_counts.values():
    if val==1:
        s1+=val
print("Medical single-node communities:", s1)

Medical single-node communities: 588

In [6]:
medical_communities_counts

Counter({0: 2022,
         1: 1778,
         2: 1588,
         3: 1578,
         4: 1527,
         5: 1448,
         6: 1427,
         7: 1317,
         8: 1294,
         9: 1236,
         10: 1200,
         11: 1195,
         12: 1182,
         13: 1105,
         14: 1097,
         15: 1074,
         16: 979,
         17: 963,
         18: 961,
         19: 852,
         20: 847,
         21: 797,
         22: 705,
         23: 648,
         24: 591,
         25: 374,
         26: 354,
         27: 260,
         28: 244,
         29: 232,
         30: 216,
         31: 211,
         32: 90,
         33: 51,
         34: 25,
         35: 16,
         36: 11,
         38: 10,
         37: 10,
         39: 9,
         40: 8,
         41: 4,
         42: 3,
         43: 1,
         44: 1,
         45: 1,
         46: 1,
         47: 1,
         48: 1,
         49: 1,
         50: 1,
         51: 1,
         52: 1,
         53: 1,
         54: 1,
         55: 1,
         56: 1,
         57: 1,
         58: 1,
         59: 1,
         60: 1,
         61: 1,
         62: 1,
         63: 1,
         64: 1,
         65: 1,
         66: 1,
         67: 1,
         68: 1,
         69: 1,
         70: 1,
         71: 1,
         72: 1,
         73: 1,
         74: 1,
         75: 1,
         76: 1,
         77: 1,
         78: 1,
         79: 1,
         80: 1,
         81: 1,
         82: 1,
         83: 1,
         84: 1,
         85: 1,
         86: 1,
         87: 1,
         88: 1,
         89: 1,
         90: 1,
         91: 1,
         92: 1,
         93: 1,
         94: 1,
         95: 1,
         96: 1,
         97: 1,
         98: 1,
         99: 1,
         100: 1,
         101: 1,
         102: 1,
         103: 1,
         104: 1,
         105: 1,
         106: 1,
         107: 1,
         108: 1,
         109: 1,
         110: 1,
         111: 1,
         112: 1,
         113: 1,
         114: 1,
         115: 1,
         116: 1,
         117: 1,
         118: 1,
         119: 1,
         120: 1,
         121: 1,
         122: 1,
         123: 1,
         124: 1,
         125: 1,
         126: 1,
         127: 1,
         128: 1,
         129: 1,
         130: 1,
         131: 1,
         132: 1,
         133: 1,
         134: 1,
         135: 1,
         136: 1,
         137: 1,
         138: 1,
         139: 1,
         140: 1,
         141: 1,
         142: 1,
         143: 1,
         144: 1,
         145: 1,
         146: 1,
         147: 1,
         148: 1,
         149: 1,
         150: 1,
         151: 1,
         152: 1,
         153: 1,
         154: 1,
         155: 1,
         156: 1,
         157: 1,
         158: 1,
         159: 1,
         160: 1,
         161: 1,
         162: 1,
         163: 1,
         164: 1,
         165: 1,
         166: 1,
         167: 1,
         168: 1,
         169: 1,
         170: 1,
         171: 1,
         172: 1,
         173: 1,
         174: 1,
         175: 1,
         176: 1,
         177: 1,
         178: 1,
         179: 1,
         180: 1,
         181: 1,
         182: 1,
         183: 1,
         184: 1,
         185: 1,
         186: 1,
         187: 1,
         188: 1,
         189: 1,
         190: 1,
         191: 1,
         192: 1,
         193: 1,
         194: 1,
         195: 1,
         196: 1,
         197: 1,
         198: 1,
         199: 1,
         200: 1,
         201: 1,
         202: 1,
         203: 1,
         204: 1,
         205: 1,
         206: 1,
         207: 1,
         208: 1,
         209: 1,
         210: 1,
         211: 1,
         212: 1,
         213: 1,
         214: 1,
         215: 1,
         216: 1,
         217: 1,
         218: 1,
         219: 1,
         220: 1,
         221: 1,
         222: 1,
         223: 1,
         224: 1,
         225: 1,
         226: 1,
         227: 1,
         228: 1,
         229: 1,
         230: 1,
         231: 1,
         232: 1,
         233: 1,
         234: 1,
         235: 1,
         236: 1,
         237: 1,
         238: 1,
         239: 1,
         240: 1,
         241: 1,
         242: 1,
         243: 1,
         244: 1,
         245: 1,
         246: 1,
         247: 1,
         248: 1,
         249: 1,
         250: 1,
         251: 1,
         252: 1,
         253: 1,
         254: 1,
         255: 1,
         256: 1,
         257: 1,
         258: 1,
         259: 1,
         260: 1,
         261: 1,
         262: 1,
         263: 1,
         264: 1,
         265: 1,
         266: 1,
         267: 1,
         268: 1,
         269: 1,
         270: 1,
         271: 1,
         272: 1,
         273: 1,
         274: 1,
         275: 1,
         276: 1,
         277: 1,
         278: 1,
         279: 1,
         280: 1,
         281: 1,
         282: 1,
         283: 1,
         284: 1,
         285: 1,
         286: 1,
         287: 1,
         288: 1,
         289: 1,
         290: 1,
         291: 1,
         292: 1,
         293: 1,
         294: 1,
         295: 1,
         296: 1,
         297: 1,
         298: 1,
         299: 1,
         300: 1,
         301: 1,
         302: 1,
         303: 1,
         304: 1,
         305: 1,
         306: 1,
         307: 1,
         308: 1,
         309: 1,
         310: 1,
         311: 1,
         312: 1,
         313: 1,
         314: 1,
         315: 1,
         316: 1,
         317: 1,
         318: 1,
         319: 1,
         320: 1,
         321: 1,
         322: 1,
         323: 1,
         324: 1,
         325: 1,
         326: 1,
         327: 1,
         328: 1,
         329: 1,
         330: 1,
         331: 1,
         332: 1,
         333: 1,
         334: 1,
         335: 1,
         336: 1,
         337: 1,
         338: 1,
         339: 1,
         340: 1,
         341: 1,
         342: 1,
         343: 1,
         344: 1,
         345: 1,
         346: 1,
         347: 1,
         348: 1,
         349: 1,
         350: 1,
         351: 1,
         352: 1,
         353: 1,
         354: 1,
         355: 1,
         356: 1,
         357: 1,
         358: 1,
         359: 1,
         360: 1,
         361: 1,
         362: 1,
         363: 1,
         364: 1,
         365: 1,
         366: 1,
         367: 1,
         368: 1,
         369: 1,
         370: 1,
         371: 1,
         372: 1,
         373: 1,
         374: 1,
         375: 1,
         376: 1,
         377: 1,
         378: 1,
         379: 1,
         380: 1,
         381: 1,
         382: 1,
         383: 1,
         384: 1,
         385: 1,
         386: 1,
         387: 1,
         388: 1,
         389: 1,
         390: 1,
         391: 1,
         392: 1,
         393: 1,
         394: 1,
         395: 1,
         396: 1,
         397: 1,
         398: 1,
         399: 1,
         400: 1,
         401: 1,
         402: 1,
         403: 1,
         404: 1,
         405: 1,
         406: 1,
         407: 1,
         408: 1,
         409: 1,
         410: 1,
         411: 1,
         412: 1,
         413: 1,
         414: 1,
         415: 1,
         416: 1,
         417: 1,
         418: 1,
         419: 1,
         420: 1,
         421: 1,
         422: 1,
         423: 1,
         424: 1,
         425: 1,
         426: 1,
         427: 1,
         428: 1,
         429: 1,
         430: 1,
         431: 1,
         432: 1,
         433: 1,
         434: 1,
         435: 1,
         436: 1,
         437: 1,
         438: 1,
         439: 1,
         440: 1,
         441: 1,
         442: 1,
         443: 1,
         444: 1,
         445: 1,
         446: 1,
         447: 1,
         448: 1,
         449: 1,
         450: 1,
         451: 1,
         452: 1,
         453: 1,
         454: 1,
         455: 1,
         456: 1,
         457: 1,
         458: 1,
         459: 1,
         460: 1,
         461: 1,
         462: 1,
         463: 1,
         464: 1,
         465: 1,
         466: 1,
         467: 1,
         468: 1,
         469: 1,
         470: 1,
         471: 1,
         472: 1,
         473: 1,
         474: 1,
         475: 1,
         476: 1,
         477: 1,
         478: 1,
         479: 1,
         480: 1,
         481: 1,
         482: 1,
         483: 1,
         484: 1,
         485: 1,
         486: 1,
         487: 1,
         488: 1,
         489: 1,
         490: 1,
         491: 1,
         492: 1,
         493: 1,
         494: 1,
         495: 1,
         496: 1,
         497: 1,
         498: 1,
         499: 1,
         500: 1,
         501: 1,
         502: 1,
         503: 1,
         504: 1,
         505: 1,
         506: 1,
         507: 1,
         508: 1,
         509: 1,
         510: 1,
         511: 1,
         512: 1,
         513: 1,
         514: 1,
         515: 1,
         516: 1,
         517: 1,
         518: 1,
         519: 1,
         520: 1,
         521: 1,
         522: 1,
         523: 1,
         524: 1,
         525: 1,
         526: 1,
         527: 1,
         528: 1,
         529: 1,
         530: 1,
         531: 1,
         532: 1,
         533: 1,
         534: 1,
         535: 1,
         536: 1,
         537: 1,
         538: 1,
         539: 1,
         540: 1,
         541: 1,
         542: 1,
         543: 1,
         544: 1,
         545: 1,
         546: 1,
         547: 1,
         548: 1,
         549: 1,
         550: 1,
         551: 1,
         552: 1,
         553: 1,
         554: 1,
         555: 1,
         556: 1,
         557: 1,
         558: 1,
         559: 1,
         560: 1,
         561: 1,
         562: 1,
         563: 1,
         564: 1,
         565: 1,
         566: 1,
         567: 1,
         568: 1,
         569: 1,
         570: 1,
         571: 1,
         572: 1,
         573: 1,
         574: 1,
         575: 1,
         576: 1,
         577: 1,
         578: 1,
         579: 1,
         580: 1,
         581: 1,
         582: 1,
         583: 1,
         584: 1,
         585: 1,
         586: 1,
         587: 1,
         588: 1,
         589: 1,
         590: 1,
         591: 1,
         592: 1,
         593: 1,
         594: 1,
         595: 1,
         596: 1,
         597: 1,
         598: 1,
         599: 1,
         600: 1,
         601: 1,
         602: 1,
         603: 1,
         604: 1,
         605: 1,
         606: 1,
         607: 1,
         608: 1,
         609: 1,
         610: 1,
         611: 1,
         612: 1,
         613: 1,
         614: 1,
         615: 1,
         616: 1,
         617: 1,
         618: 1,
         619: 1,
         620: 1,
         621: 1,
         622: 1,
         623: 1,
         624: 1,
         625: 1,
         626: 1,
         627: 1,
         628: 1,
         629: 1,
         630: 1})

In [7]:
communities_medical = defaultdict(list)
for node_id, community_id in medical_communities.items():
    #if medical_g2[node_id].node_type == "N":
    #    continue
    communities_medical[community_id].append(node_id)

In [8]:
communities_medical

defaultdict(list,
            {22: ['medical-0-S-0',
              'medical-0-S-0-R-1',
              'medical-15-S-3-R-10',
              'medical-15-S-5',
              'medical-15-S-5-R-0',
              'medical-15-S-5-R-1',
              'medical-15-S-5-R-2',
              'medical-16-S-1',
              'medical-16-S-1-R-0',
              'medical-16-S-1-R-1',
              'medical-16-S-1-R-2',
              'medical-16-S-1-R-3',
              'medical-16-S-1-R-4',
              'medical-16-S-1-R-5',
              'medical-16-S-1-R-7',
              'medical-16-S-1-R-9',
              'medical-16-S-1-R-11',
              'medical-20-S-4-R-5',
              'medical-32-S-0-R-8',
              'medical-33-S-1-R-3',
              'medical-35-S-1',
              'medical-35-S-1-R-0',
              'medical-35-S-1-R-2',
              'medical-35-S-1-R-3',
              'medical-64-S-0-R-0',
              'medical-118-S-2-R-13',
              'medical-118-S-2-R-14',
              'medical-118-S-2-R-15',
              'medical-118-S-2-R-16',
              'medical-141-S-4-R-0',
              'medical-141-S-4-R-1',
              'medical-142-S-0-R-0',
              'medical-142-S-0-R-1',
              'medical-142-S-2-R-0',
              'medical-148-S-6',
              'medical-148-S-6-R-0',
              'medical-148-S-6-R-1',
              'medical-149-S-2',
              'medical-149-S-2-R-0',
              'medical-149-S-2-R-1',
              'medical-149-S-2-R-2',
              'medical-149-S-2-R-3',
              'medical-149-S-2-R-4',
              'medical-149-S-2-R-5',
              'medical-149-S-2-R-6',
              'medical-149-S-2-R-7',
              'medical-149-S-2-R-8',
              'medical-149-S-2-R-9',
              'medical-149-S-3',
              'medical-149-S-3-R-0',
              'medical-149-S-3-R-1',
              'medical-149-S-3-R-6',
              'medical-149-S-3-R-11',
              'medical-149-S-3-R-12',
              'medical-149-S-3-R-13',
              'medical-149-S-3-R-14',
              'medical-149-S-3-R-15',
              'medical-149-S-3-R-16',
              'medical-149-S-3-R-17',
              'medical-149-S-3-R-18',
              'medical-149-S-3-R-19',
              'medical-149-S-3-R-20',
              'medical-149-S-3-R-21',
              'medical-149-S-4',
              'medical-149-S-4-R-0',
              'medical-149-S-4-R-3',
              'medical-149-S-4-R-4',
              'medical-149-S-4-R-5',
              'medical-149-S-4-R-9',
              'medical-149-S-4-R-10',
              'medical-149-S-4-R-11',
              'medical-149-S-4-R-12',
              'medical-149-S-4-R-13',
              'medical-149-S-4-R-15',
              'medical-149-S-4-R-16',
              'medical-149-S-4-R-17',
              'medical-150-S-0',
              'medical-150-S-0-R-0',
              'medical-150-S-0-R-1',
              'medical-150-S-0-R-2',
              'medical-157-S-5-R-0',
              'medical-158-S-3-R-5',
              'medical-159-S-1-R-0',
              'medical-160-S-1-R-0',
              'medical-161-S-0-R-1',
              'medical-286-S-0-R-12',
              'medical-317-S-4-R-5',
              'medical-318-S-0-R-2',
              'medical-318-S-0-R-5',
              'medical-318-S-0-R-6',
              'medical-331-S-5',
              'medical-331-S-5-R-0',
              'medical-331-S-5-R-1',
              'medical-331-S-5-R-2',
              'medical-331-S-5-R-3',
              'medical-331-S-5-R-4',
              'medical-331-S-5-R-5',
              'medical-331-S-5-R-8',
              'medical-366-S-4',
              'medical-366-S-4-R-0',
              'medical-366-S-4-R-2',
              'medical-366-S-4-R-3',
              'medical-366-S-4-R-4',
              'medical-366-S-4-R-5',
              'medical-366-S-4-R-6',
              'medical-366-S-4-R-7',
              'medical-366-S-4-R-9',
              'medical-367-S-0',
              'medical-367-S-0-R-0',
              'medical-367-S-0-R-1',
              'medical-367-S-0-R-2',
              'medical-367-S-0-R-3',
              'medical-367-S-0-R-4',
              'medical-367-S-0-R-5',
              'medical-367-S-1',
              'medical-367-S-1-R-0',
              'medical-367-S-1-R-1',
              'medical-367-S-1-R-2',
              'medical-369-S-7-R-0',
              'medical-370-S-0-R-0',
              'medical-372-S-0',
              'medical-372-S-0-R-0',
              'medical-372-S-0-R-1',
              'medical-372-S-0-R-2',
              'medical-372-S-0-R-3',
              'medical-373-S-3-R-1',
              'medical-373-S-4-R-0',
              'medical-373-S-4-R-4',
              'medical-374-S-0-R-1',
              'medical-374-S-0-R-3',
              'medical-374-S-0-R-4',
              'medical-374-S-1',
              'medical-374-S-1-R-1',
              'medical-374-S-1-R-2',
              'medical-374-S-1-R-3',
              'medical-374-S-1-R-4',
              'medical-374-S-1-R-5',
              'medical-374-S-1-R-6',
              'medical-374-S-1-R-7',
              'medical-374-S-1-R-8',
              'medical-374-S-1-R-9',
              'medical-374-S-1-R-10',
              'medical-374-S-1-R-11',
              'medical-374-S-1-R-12',
              'medical-374-S-1-R-14',
              'medical-374-S-1-R-15',
              'medical-374-S-2',
              'medical-374-S-2-R-0',
              'medical-374-S-2-R-1',
              'medical-374-S-2-R-2',
              'medical-374-S-2-R-3',
              'medical-374-S-2-R-4',
              'medical-374-S-2-R-5',
              'medical-374-S-2-R-6',
              'medical-374-S-2-R-7',
              'medical-374-S-2-R-8',
              'medical-374-S-2-R-9',
              'medical-374-S-2-R-10',
              'medical-374-S-2-R-11',
              'medical-374-S-2-R-12',
              'medical-374-S-2-R-13',
              'medical-374-S-2-R-14',
              'medical-374-S-2-R-15',
              'medical-374-S-2-R-18',
              'medical-375-S-0',
              'medical-375-S-0-R-0',
              'medical-375-S-0-R-1',
              'medical-375-S-0-R-2',
              'medical-375-S-0-R-3',
              'medical-375-S-1',
              'medical-375-S-1-R-0',
              'medical-375-S-1-R-1',
              'medical-375-S-1-R-2',
              'medical-375-S-1-R-3',
              'medical-375-S-1-R-4',
              'medical-375-S-1-R-5',
              'medical-375-S-1-R-6',
              'medical-375-S-1-R-7',
              'medical-375-S-2-R-8',
              'medical-375-S-4',
              'medical-375-S-4-R-0',
              'medical-375-S-4-R-1',
              'medical-376-S-1-R-0',
              'medical-376-S-2',
              'medical-376-S-2-R-0',
              'medical-376-S-2-R-1',
              'medical-376-S-3',
              'medical-376-S-3-R-0',
              'medical-376-S-3-R-1',
              'medical-376-S-3-R-2',
              'medical-376-S-3-R-3',
              'medical-381-S-0-R-2',
              'medical-381-S-6-R-3',
              'medical-382-S-1-R-2',
              'medical-384-S-5-R-0',
              'medical-384-S-5-R-3',
              'medical-387-S-2',
              'medical-387-S-2-R-0',
              'medical-387-S-2-R-1',
              'medical-389-S-0-R-3',
              'medical-389-S-0-R-4',
              'medical-389-S-0-R-7',
              'medical-389-S-0-R-8',
              'medical-389-S-0-R-9',
              'medical-389-S-0-R-10',
              'medical-390-S-0-R-1',
              'medical-391-S-6-R-0',
              'medical-392-S-0-R-0',
              'medical-392-S-1-R-5',
              'medical-392-S-1-R-6',
              'medical-392-S-1-R-7',
              'medical-394-S-3',
              'medical-394-S-3-R-0',
              'medical-394-S-3-R-2',
              'medical-394-S-3-R-3',
              'medical-394-S-3-R-6',
              'medical-395-S-2-R-0',
              'medical-395-S-3-R-5',
              'medical-400-S-2-R-1',
              'medical-402-S-2-R-0',
              'medical-402-S-2-R-1',
              'medical-402-S-2-R-2',
              'medical-402-S-5-R-0',
              'medical-402-S-5-R-1',
              'medical-402-S-5-R-2',
              'medical-402-S-5-R-5',
              'medical-402-S-6',
              'medical-402-S-6-R-0',
              'medical-402-S-6-R-1',
              'medical-402-S-6-R-2',
              'medical-402-S-6-R-3',
              'medical-403-S-0-R-0',
              'medical-403-S-0-R-1',
              'medical-403-S-0-R-2',
              'medical-403-S-0-R-5',
              'medical-403-S-1',
              'medical-403-S-1-R-0',
              'medical-403-S-1-R-1',
              'medical-403-S-1-R-2',
              'medical-403-S-1-R-3',
              'medical-403-S-1-R-4',
              'medical-403-S-1-R-5',
              'medical-403-S-1-R-6',
              'medical-403-S-1-R-7',
              'medical-403-S-1-R-8',
              'medical-405-S-2-R-0',
              'medical-405-S-2-R-1',
              'medical-405-S-2-R-6',
              'medical-405-S-2-R-7',
              'medical-419-S-4',
              'medical-419-S-4-R-0',
              'medical-419-S-4-R-1',
              'medical-419-S-4-R-2',
              'medical-419-S-4-R-3',
              'medical-419-S-4-R-4',
              'medical-419-S-4-R-5',
              'medical-419-S-4-R-8',
              'medical-420-S-1',
              'medical-420-S-1-R-0',
              'medical-420-S-1-R-1',
              'medical-420-S-1-R-2',
              'medical-420-S-1-R-4',
              'medical-420-S-1-R-5',
              'medical-420-S-1-R-6',
              'medical-428-S-3-R-5',
              'medical-428-S-3-R-6',
              'medical-428-S-3-R-7',
              'medical-482-S-2-R-5',
              'medical-482-S-2-R-7',
              'medical-501-S-5-R-6',
              'medical-510-S-2-R-1',
              'medical-511-S-0-R-1',
              'medical-515-S-2',
              'medical-515-S-2-R-0',
              'medical-515-S-2-R-1',
              'medical-515-S-2-R-4',
              'medical-518-S-0-R-0',
              'medical-518-S-0-R-1',
              'medical-518-S-0-R-9',
              'medical-518-S-3-R-0',
              'medical-518-S-3-R-1',
              'medical-519-S-0-R-1',
              'medical-519-S-1',
              'medical-519-S-1-R-1',
              'medical-519-S-1-R-2',
              'medical-519-S-1-R-3',
              'medical-519-S-1-R-4',
              'medical-519-S-1-R-5',
              'medical-519-S-1-R-6',
              'medical-519-S-1-R-7',
              'medical-519-S-1-R-8',
              'medical-519-S-1-R-9',
              'medical-519-S-1-R-10',
              'medical-519-S-1-R-11',
              'medical-519-S-1-R-12',
              'medical-519-S-1-R-13',
              'medical-519-S-1-R-14',
              'medical-519-S-2',
              'medical-519-S-2-R-0',
              'medical-519-S-2-R-1',
              'medical-519-S-2-R-2',
              'medical-519-S-2-R-3',
              'medical-519-S-2-R-4',
              'medical-519-S-2-R-5',
              'medical-519-S-2-R-6',
              'medical-519-S-2-R-7',
              'medical-519-S-2-R-8',
              'medical-519-S-2-R-9',
              'medical-520-S-0',
              'medical-520-S-0-R-3',
              'medical-520-S-0-R-5',
              'medical-520-S-0-R-6',
              'medical-520-S-0-R-7',
              'medical-520-S-0-R-8',
              'medical-520-S-0-R-9',
              'medical-520-S-0-R-10',
              'medical-520-S-0-R-11',
              'medical-520-S-0-R-13',
              'medical-520-S-0-R-14',
              'medical-520-S-0-R-15',
              'medical-520-S-0-R-16',
              'medical-520-S-0-R-18',
              'medical-520-S-0-R-19',
              'medical-520-S-0-R-20',
              'medical-520-S-0-R-21',
              'medical-520-S-0-R-22',
              'medical-520-S-0-R-23',
              'medical-520-S-0-R-24',
              'medical-520-S-0-R-25',
              'medical-520-S-0-R-26',
              'medical-520-S-1',
              'medical-520-S-1-R-0',
              'medical-520-S-1-R-1',
              'medical-520-S-1-R-2',
              'medical-520-S-1-R-3',
              'medical-520-S-1-R-4',
              'medical-520-S-1-R-5',
              'medical-520-S-1-R-6',
              'medical-520-S-1-R-7',
              'medical-520-S-1-R-8',
              'medical-521-S-1-R-9',
              'medical-521-S-2-R-1',
              'medical-521-S-2-R-2',
              'medical-521-S-3-R-0',
              'medical-523-S-1-R-1',
              'medical-523-S-1-R-5',
              'medical-523-S-1-R-6',
              'medical-524-S-3',
              'medical-524-S-3-R-0',
              'medical-524-S-4',
              'medical-524-S-4-R-0',
              'medical-524-S-4-R-1',
              'medical-524-S-4-R-2',
              'medical-524-S-4-R-3',
              'medical-524-S-4-R-4',
              'medical-524-S-4-R-5',
              'medical-524-S-4-R-6',
              'medical-524-S-4-R-7',
              'medical-525-S-0-R-1',
              'medical-525-S-2',
              'medical-525-S-2-R-0',
              'medical-525-S-2-R-3',
              'medical-525-S-2-R-4',
              'medical-525-S-2-R-5',
              'medical-525-S-2-R-6',
              'medical-525-S-2-R-7',
              'medical-525-S-2-R-8',
              'medical-525-S-2-R-9',
              'medical-525-S-2-R-10',
              'medical-525-S-2-R-11',
              'medical-525-S-2-R-12',
              'medical-525-S-3',
              'medical-525-S-3-R-0',
              'medical-525-S-3-R-2',
              'medical-525-S-3-R-3',
              'medical-525-S-4',
              'medical-525-S-4-R-0',
              'medical-525-S-4-R-1',
              'medical-525-S-4-R-2',
              'medical-525-S-4-R-3',
              'medical-525-S-4-R-4',
              'medical-525-S-4-R-5',
              'medical-525-S-5-R-0',
              'medical-525-S-6',
              'medical-526-S-4',
              'medical-526-S-4-R-2',
              'medical-526-S-4-R-3',
              'medical-527-S-5-R-3',
              'medical-527-S-5-R-4',
              'medical-527-S-6',
              'medical-527-S-6-R-0',
              'medical-527-S-7',
              'medical-527-S-7-R-0',
              'medical-527-S-7-R-1',
              'medical-527-S-7-R-2',
              'medical-527-S-7-R-3',
              'medical-527-S-7-R-4',
              'medical-527-S-7-R-5',
              'medical-527-S-7-R-6',
              'medical-527-S-7-R-7',
              'medical-527-S-7-R-8',
              'medical-527-S-7-R-9',
              'medical-527-S-8-R-3',
              'medical-528-S-0',
              'medical-528-S-0-R-0',
              'medical-528-S-0-R-1',
              'medical-528-S-0-R-2',
              'medical-528-S-0-R-3',
              'medical-528-S-0-R-4',
              'medical-528-S-0-R-6',
              'medical-528-S-0-R-7',
              'medical-528-S-1-R-3',
              'medical-529-S-5',
              'medical-529-S-5-R-0',
              'medical-529-S-5-R-1',
              'medical-529-S-5-R-2',
              'medical-529-S-5-R-3',
              'medical-529-S-5-R-4',
              'medical-529-S-5-R-5',
              'medical-530-S-0-R-9',
              'medical-530-S-0-R-10',
              'medical-530-S-0-R-11',
              'medical-530-S-0-R-12',
              'medical-530-S-2-R-1',
              'medical-535-S-0-R-11',
              'medical-536-S-2-R-0',
              'medical-539-S-2',
              'medical-539-S-2-R-0',
              'medical-539-S-2-R-1',
              'medical-539-S-2-R-2',
              'medical-539-S-2-R-3',
              'medical-539-S-2-R-4',
              'medical-539-S-2-R-5',
              'medical-539-S-2-R-6',
              'medical-539-S-2-R-7',
              'medical-539-S-2-R-8',
              'medical-541-S-2',
              'medical-541-S-2-R-0',
              'medical-541-S-2-R-1',
              'medical-541-S-2-R-2',
              'medical-541-S-2-R-3',
              'medical-541-S-2-R-4',
              'medical-541-S-2-R-5',
              'medical-541-S-2-R-6',
              'medical-541-S-2-R-7',
              'medical-541-S-2-R-8',
              'medical-541-S-2-R-9',
              'medical-541-S-3-R-3',
              'medical-542-S-1-R-1',
              'medical-542-S-1-R-2',
              'medical-542-S-1-R-3',
              'medical-542-S-1-R-7',
              'medical-545-S-0-R-0',
              'medical-545-S-0-R-4',
              'medical-545-S-2',
              'medical-545-S-2-R-0',
              'medical-545-S-2-R-1',
              'medical-545-S-2-R-2',
              'medical-545-S-2-R-4',
              'medical-545-S-2-R-5',
              'medical-545-S-2-R-6',
              'medical-545-S-2-R-7',
              'medical-545-S-2-R-8',
              'medical-546-S-0-R-0',
              'medical-546-S-0-R-1',
              'medical-546-S-0-R-2',
              'medical-548-S-3-R-4',
              'medical-550-S-2-R-0',
              'medical-550-S-2-R-1',
              'medical-552-S-1',
              'medical-552-S-1-R-0',
              'medical-552-S-1-R-1',
              'medical-552-S-1-R-2',
              'medical-552-S-1-R-3',
              'medical-552-S-1-R-4',
              'medical-552-S-1-R-5',
              'medical-552-S-1-R-6',
              'medical-552-S-1-R-7',
              'medical-552-S-1-R-8',
              'medical-552-S-1-R-9',
              'medical-552-S-1-R-10',
              'medical-552-S-1-R-11',
              'medical-552-S-1-R-12',
              'medical-552-S-1-R-13',
              'medical-552-S-1-R-14',
              'medical-552-S-1-R-15',
              'medical-552-S-2-R-1',
              'medical-552-S-2-R-2',
              'medical-552-S-2-R-3',
              'medical-552-S-2-R-19',
              'medical-552-S-2-R-27',
              'medical-553-S-3',
              'medical-553-S-3-R-0',
              'medical-553-S-3-R-1',
              'medical-553-S-3-R-2',
              'medical-553-S-3-R-3',
              'medical-N-1',
              'medical-N-2',
              'medical-N-3',
              'medical-N-353',
              'medical-N-372',
              'medical-N-373',
              'medical-N-375',
              'medical-N-378',
              'medical-N-379',
              'medical-N-381',
              'medical-N-382',
              'medical-N-383',
              'medical-N-384',
              'medical-N-730',
              'medical-N-732',
              'medical-N-757',
              'medical-N-799',
              'medical-N-800',
              'medical-N-2244',
              'medical-N-2245',
              'medical-N-2246',
              'medical-N-2626',
              'medical-N-2634',
              'medical-N-2690',
              'medical-N-2692',
              'medical-N-2693',
              'medical-N-2694',
              'medical-N-2695',
              'medical-N-2696',
              'medical-N-2697',
              'medical-N-2698',
              'medical-N-2699',
              'medical-N-2700',
              'medical-N-2702',
              'medical-N-2703',
              'medical-N-2704',
              'medical-N-2705',
              'medical-N-2706',
              'medical-N-2707',
              'medical-N-2708',
              'medical-N-2709',
              'medical-N-2710',
              'medical-N-2711',
              'medical-N-2712',
              'medical-N-2713',
              'medical-N-2714',
              'medical-N-2715',
              'medical-N-2716',
              'medical-N-2718',
              'medical-N-2719',
              'medical-N-2720',
              'medical-N-3943',
              'medical-N-4579',
              'medical-N-4580',
              'medical-N-4581',
              'medical-N-4582',

In [ ]:
from google import genai

with open(f"{root_path}/API_KEY.txt", "r", encoding="utf-8") as f:
    API_KEY = f.read()
    
def call_gemini(text):
    client = genai.Client(api_key = API_KEY)
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=text,
    )
    return response.text

In [10]:
import time
from tqdm import tqdm

In [11]:
medical_communities_response = {}

In [16]:
from graphs.prompt.high_level_elements_generation_prompt import high_level_elements_generation_prompt

for c in tqdm(communities_medical):
    if f'medical-H-{c}' in medical_communities_response:
        continue
    semantic_count = 0
    nodes_id = communities_medical[c]
    content = []
    for nid in nodes_id:
        node = medical_g2[nid]
        if node.node_type == "S":
            semantic_count+=1
        if node.node_type in ["R", "N"]:
            continue
        content.append(node.content)
    if semantic_count < 2:
        continue
    else:
        content = "\n".join(content)
        response = call_gemini(high_level_elements_generation_prompt(content))
        medical_communities_response[f'medical-H-{c}'] = response
        time.sleep(2)

100%|██████████| 631/631 [01:37<00:00,  6.45it/s]

In [17]:
medical_communities_overview = {}

In [18]:
from graphs.prompt.high_level_overview_generation_prompt import high_level_overview_prompt
for element_id, element in tqdm(medical_communities_response.items()):
    overview_id = f"{element_id}-O-0"
    if overview_id in medical_communities_overview:
        continue
    overview = call_gemini(high_level_overview_prompt(element))
    medical_communities_overview[overview_id] = overview
    time.sleep(4)

100%|██████████| 37/37 [03:02<00:00,  4.94s/it]

In [19]:
import pandas as pd
medical_df = pd.DataFrame(list(medical_communities_response.items()), columns=["node_id", "community_summary"])
medical_df.to_parquet("data//nodes/community/medical_communities_summary.parquet")
medical_df = pd.read_parquet("data/nodes/community/medical_communities_summary.parquet")
medical_df

         node_id                                  community_summary
0   medical-H-22  Here are the distinct categories of high-level...
1   medical-H-24  Here are distinct categories of high-level inf...
2   medical-H-21  Here are distinct categories of high-level inf...
3   medical-H-15  Here are the distinct categories of high-level...
4    medical-H-2  Here's a breakdown of distinct high-level info...
5   medical-H-14  Here are the distinct categories of high-level...
6   medical-H-10  Here are distinct categories of high-level inf...
7    medical-H-5  Here are the distinct categories of high-level...
8   medical-H-11  Here's a breakdown of the distinct categories ...
9    medical-H-8  Here's a breakdown of distinct categories of h...
10  medical-H-26  Here are the distinct categories of high-level...
11  medical-H-20  Here are the distinct categories of high-level...
12  medical-H-23  Here are the distinct categories of high-level...
13  medical-H-13  Here's a breakdown of the distinct categories ...
14  medical-H-17  Here are the distinct categories of high-level...
15   medical-H-1  Here's a breakdown of the distinct, high-level...
16  medical-H-12  Here's a breakdown of the distinct, high-level...
17   medical-H-7  Here are the distinct categories of high-level...
18   medical-H-9  Here are the distinct categories of high-level...
19   medical-H-6  Here are distinct categories of high-level inf...
20   medical-H-3  Here's a breakdown of the distinct categories ...
21   medical-H-0  Here are the distinct categories of high-level...
22  medical-H-19  Here are distinct categories of high-level inf...
23  medical-H-16  Here are the distinct categories of high-level...
24   medical-H-4  Here are the distinct categories of high-level...
25  medical-H-18  Here are the distinct categories of high-level...
26  medical-H-32  Here are the distinct categories of high-level...
27  medical-H-25  Here are the distinct categories of high-level...
28  medical-H-31  Here are distinct categories of high-level inf...
29  medical-H-27  Here are distinct categories of high-level inf...
30  medical-H-30  Here are the distinct categories of high-level...
31  medical-H-34  Here are the distinct categories of high-level...
32  medical-H-28  Here are the distinct categories of high-level...
33  medical-H-33  Here are distinct categories of high-level inf...
34  medical-H-35  Here's an extraction of distinct categories of...
35  medical-H-29  Here are the distinct categories of high-level...
36  medical-H-37  Here are the distinct categories of high-level...

In [20]:
medical_overview = pd.DataFrame(list(medical_communities_overview.items()), columns=["node_id", "community_overview"])
medical_overview.to_parquet("data/nodes/community/medical_communities_overview.parquet")
medical_overview = pd.read_parquet("data/nodes/community/medical_communities_overview.parquet")
medical_overview

             node_id                                 community_overview
0   medical-H-22-O-0  HPV Cancer Etiology Diagnosis Screening Vaccin...
1   medical-H-24-O-0  Skin Cancer: Origins, Risk Factors, Appearance...
2   medical-H-21-O-0  Cancer Patient Empowerment, Guidance, Genetics...
3   medical-H-15-O-0  Cancer genetics molecular diagnostics biomarke...
4    medical-H-2-O-0  Cancer Diagnosis, Staging, Treatment, and Prog...
5   medical-H-14-O-0  Cancer Treatment, Fertility, Side Effects, Dia...
6   medical-H-10-O-0  Cancer Diagnosis Treatment Planning Testing Me...
7    medical-H-5-O-0                  Cancer Patient Journey Management
8   medical-H-11-O-0  Cancer Diagnosis, Staging, Grading, Biomarkers...
9    medical-H-8-O-0  Endocrine System, Hormone Function, Adrenal Gl...
10  medical-H-26-O-0  Cancer Metastasis Diagnosis Staging Treatment ...
11  medical-H-20-O-0  Colorectal and Anal Cancer: Types, Genetics, D...
12  medical-H-23-O-0  Cancer Types, Risks, Pathology, Diagnosis, Tre...
13  medical-H-13-O-0  Prostate Cancer: Overview, Risk Factors, Sympt...
14  medical-H-17-O-0  Bladder Cancer Diagnosis, Treatment, and Manag...
15   medical-H-1-O-0  Cancer Diagnosis, Staging, Treatment, and Pati...
16  medical-H-12-O-0  Medical history, family history, genetics, tes...
17   medical-H-7-O-0  Lymphoma Pathophysiology Glioma Ovarian Cancer...
18   medical-H-9-O-0  Head and Neck Cancer: Anatomy, Pathology, Diag...
19   medical-H-6-O-0  Lymphatic System, Cancer Metastasis, Diagnosis...
20   medical-H-3-O-0            Thyroid Cancer Treatment and Management
21   medical-H-0-O-0  Blood Cancers: Identification, Cellular Basis,...
22  medical-H-19-O-0  Cancer Clinical Trials: Process, Participation...
23  medical-H-16-O-0  Cancer Diagnosis, Staging, Biomarkers, Mutatio...
24   medical-H-4-O-0  Cancer Systemic Therapy Modalities and Management
25  medical-H-18-O-0  Cancer Anatomy, Progression, Risk Factors, Dia...
26  medical-H-32-O-0  PD-L1, TMB, Immune Checkpoint Inhibition, Biom...
27  medical-H-25-O-0  Cancer Care: Multidisciplinary Teams, Patient ...
28  medical-H-31-O-0  Acute Lymphoblastic Leukemia Classification, B...
29  medical-H-27-O-0  Cancer Patient Support, Mental Health, Physica...
30  medical-H-30-O-0  Lymphoma Types, Diagnosis, Grading, Transforma...
31  medical-H-34-O-0  Cancer Treatment Categorization Framework Evid...
32  medical-H-28-O-0  Chemotherapy Drug Classes, Mechanisms, Targete...
33  medical-H-33-O-0  Ovarian, Peritoneal, Fallopian Tube Cancers: C...
34  medical-H-35-O-0  Infant ALL Treatment Protocols Pediatric Oncol...
35  medical-H-29-O-0  HER2 Testing, Breast Cancer Treatment, Targete...
36  medical-H-37-O-0  Healthcare Communication Patient Access Contac...

In [21]:
with open(f"{root_path}/graphs/data/nodes/community/medical_communities.pkl", "wb") as f:
    pickle.dump(communities_medical, f)
with open(f"{root_path}/graphs/data/nodes/community/medical_communities.pkl", "rb") as f:
    communities_medical_loaded = pickle.load(f)

In [22]:
communities_medical_loaded

defaultdict(list,
            {22: ['medical-0-S-0',
              'medical-0-S-0-R-1',
              'medical-15-S-3-R-10',
              'medical-15-S-5',
              'medical-15-S-5-R-0',
              'medical-15-S-5-R-1',
              'medical-15-S-5-R-2',
              'medical-16-S-1',
              'medical-16-S-1-R-0',
              'medical-16-S-1-R-1',
              'medical-16-S-1-R-2',
              'medical-16-S-1-R-3',
              'medical-16-S-1-R-4',
              'medical-16-S-1-R-5',
              'medical-16-S-1-R-7',
              'medical-16-S-1-R-9',
              'medical-16-S-1-R-11',
              'medical-20-S-4-R-5',
              'medical-32-S-0-R-8',
              'medical-33-S-1-R-3',
              'medical-35-S-1',
              'medical-35-S-1-R-0',
              'medical-35-S-1-R-2',
              'medical-35-S-1-R-3',
              'medical-64-S-0-R-0',
              'medical-118-S-2-R-13',
              'medical-118-S-2-R-14',
              'medical-118-S-2-R-15',
              'medical-118-S-2-R-16',
              'medical-141-S-4-R-0',
              'medical-141-S-4-R-1',
              'medical-142-S-0-R-0',
              'medical-142-S-0-R-1',
              'medical-142-S-2-R-0',
              'medical-148-S-6',
              'medical-148-S-6-R-0',
              'medical-148-S-6-R-1',
              'medical-149-S-2',
              'medical-149-S-2-R-0',
              'medical-149-S-2-R-1',
              'medical-149-S-2-R-2',
              'medical-149-S-2-R-3',
              'medical-149-S-2-R-4',
              'medical-149-S-2-R-5',
              'medical-149-S-2-R-6',
              'medical-149-S-2-R-7',
              'medical-149-S-2-R-8',
              'medical-149-S-2-R-9',
              'medical-149-S-3',
              'medical-149-S-3-R-0',
              'medical-149-S-3-R-1',
              'medical-149-S-3-R-6',
              'medical-149-S-3-R-11',
              'medical-149-S-3-R-12',
              'medical-149-S-3-R-13',
              'medical-149-S-3-R-14',
              'medical-149-S-3-R-15',
              'medical-149-S-3-R-16',
              'medical-149-S-3-R-17',
              'medical-149-S-3-R-18',
              'medical-149-S-3-R-19',
              'medical-149-S-3-R-20',
              'medical-149-S-3-R-21',
              'medical-149-S-4',
              'medical-149-S-4-R-0',
              'medical-149-S-4-R-3',
              'medical-149-S-4-R-4',
              'medical-149-S-4-R-5',
              'medical-149-S-4-R-9',
              'medical-149-S-4-R-10',
              'medical-149-S-4-R-11',
              'medical-149-S-4-R-12',
              'medical-149-S-4-R-13',
              'medical-149-S-4-R-15',
              'medical-149-S-4-R-16',
              'medical-149-S-4-R-17',
              'medical-150-S-0',
              'medical-150-S-0-R-0',
              'medical-150-S-0-R-1',
              'medical-150-S-0-R-2',
              'medical-157-S-5-R-0',
              'medical-158-S-3-R-5',
              'medical-159-S-1-R-0',
              'medical-160-S-1-R-0',
              'medical-161-S-0-R-1',
              'medical-286-S-0-R-12',
              'medical-317-S-4-R-5',
              'medical-318-S-0-R-2',
              'medical-318-S-0-R-5',
              'medical-318-S-0-R-6',
              'medical-331-S-5',
              'medical-331-S-5-R-0',
              'medical-331-S-5-R-1',
              'medical-331-S-5-R-2',
              'medical-331-S-5-R-3',
              'medical-331-S-5-R-4',
              'medical-331-S-5-R-5',
              'medical-331-S-5-R-8',
              'medical-366-S-4',
              'medical-366-S-4-R-0',
              'medical-366-S-4-R-2',
              'medical-366-S-4-R-3',
              'medical-366-S-4-R-4',
              'medical-366-S-4-R-5',
              'medical-366-S-4-R-6',
              'medical-366-S-4-R-7',
              'medical-366-S-4-R-9',
              'medical-367-S-0',
              'medical-367-S-0-R-0',
              'medical-367-S-0-R-1',
              'medical-367-S-0-R-2',
              'medical-367-S-0-R-3',
              'medical-367-S-0-R-4',
              'medical-367-S-0-R-5',
              'medical-367-S-1',
              'medical-367-S-1-R-0',
              'medical-367-S-1-R-1',
              'medical-367-S-1-R-2',
              'medical-369-S-7-R-0',
              'medical-370-S-0-R-0',
              'medical-372-S-0',
              'medical-372-S-0-R-0',
              'medical-372-S-0-R-1',
              'medical-372-S-0-R-2',
              'medical-372-S-0-R-3',
              'medical-373-S-3-R-1',
              'medical-373-S-4-R-0',
              'medical-373-S-4-R-4',
              'medical-374-S-0-R-1',
              'medical-374-S-0-R-3',
              'medical-374-S-0-R-4',
              'medical-374-S-1',
              'medical-374-S-1-R-1',
              'medical-374-S-1-R-2',
              'medical-374-S-1-R-3',
              'medical-374-S-1-R-4',
              'medical-374-S-1-R-5',
              'medical-374-S-1-R-6',
              'medical-374-S-1-R-7',
              'medical-374-S-1-R-8',
              'medical-374-S-1-R-9',
              'medical-374-S-1-R-10',
              'medical-374-S-1-R-11',
              'medical-374-S-1-R-12',
              'medical-374-S-1-R-14',
              'medical-374-S-1-R-15',
              'medical-374-S-2',
              'medical-374-S-2-R-0',
              'medical-374-S-2-R-1',
              'medical-374-S-2-R-2',
              'medical-374-S-2-R-3',
              'medical-374-S-2-R-4',
              'medical-374-S-2-R-5',
              'medical-374-S-2-R-6',
              'medical-374-S-2-R-7',
              'medical-374-S-2-R-8',
              'medical-374-S-2-R-9',
              'medical-374-S-2-R-10',
              'medical-374-S-2-R-11',
              'medical-374-S-2-R-12',
              'medical-374-S-2-R-13',
              'medical-374-S-2-R-14',
              'medical-374-S-2-R-15',
              'medical-374-S-2-R-18',
              'medical-375-S-0',
              'medical-375-S-0-R-0',
              'medical-375-S-0-R-1',
              'medical-375-S-0-R-2',
              'medical-375-S-0-R-3',
              'medical-375-S-1',
              'medical-375-S-1-R-0',
              'medical-375-S-1-R-1',
              'medical-375-S-1-R-2',
              'medical-375-S-1-R-3',
              'medical-375-S-1-R-4',
              'medical-375-S-1-R-5',
              'medical-375-S-1-R-6',
              'medical-375-S-1-R-7',
              'medical-375-S-2-R-8',
              'medical-375-S-4',
              'medical-375-S-4-R-0',
              'medical-375-S-4-R-1',
              'medical-376-S-1-R-0',
              'medical-376-S-2',
              'medical-376-S-2-R-0',
              'medical-376-S-2-R-1',
              'medical-376-S-3',
              'medical-376-S-3-R-0',
              'medical-376-S-3-R-1',
              'medical-376-S-3-R-2',
              'medical-376-S-3-R-3',
              'medical-381-S-0-R-2',
              'medical-381-S-6-R-3',
              'medical-382-S-1-R-2',
              'medical-384-S-5-R-0',
              'medical-384-S-5-R-3',
              'medical-387-S-2',
              'medical-387-S-2-R-0',
              'medical-387-S-2-R-1',
              'medical-389-S-0-R-3',
              'medical-389-S-0-R-4',
              'medical-389-S-0-R-7',
              'medical-389-S-0-R-8',
              'medical-389-S-0-R-9',
              'medical-389-S-0-R-10',
              'medical-390-S-0-R-1',
              'medical-391-S-6-R-0',
              'medical-392-S-0-R-0',
              'medical-392-S-1-R-5',
              'medical-392-S-1-R-6',
              'medical-392-S-1-R-7',
              'medical-394-S-3',
              'medical-394-S-3-R-0',
              'medical-394-S-3-R-2',
              'medical-394-S-3-R-3',
              'medical-394-S-3-R-6',
              'medical-395-S-2-R-0',
              'medical-395-S-3-R-5',
              'medical-400-S-2-R-1',
              'medical-402-S-2-R-0',
              'medical-402-S-2-R-1',
              'medical-402-S-2-R-2',
              'medical-402-S-5-R-0',
              'medical-402-S-5-R-1',
              'medical-402-S-5-R-2',
              'medical-402-S-5-R-5',
              'medical-402-S-6',
              'medical-402-S-6-R-0',
              'medical-402-S-6-R-1',
              'medical-402-S-6-R-2',
              'medical-402-S-6-R-3',
              'medical-403-S-0-R-0',
              'medical-403-S-0-R-1',
              'medical-403-S-0-R-2',
              'medical-403-S-0-R-5',
              'medical-403-S-1',
              'medical-403-S-1-R-0',
              'medical-403-S-1-R-1',
              'medical-403-S-1-R-2',
              'medical-403-S-1-R-3',
              'medical-403-S-1-R-4',
              'medical-403-S-1-R-5',
              'medical-403-S-1-R-6',
              'medical-403-S-1-R-7',
              'medical-403-S-1-R-8',
              'medical-405-S-2-R-0',
              'medical-405-S-2-R-1',
              'medical-405-S-2-R-6',
              'medical-405-S-2-R-7',
              'medical-419-S-4',
              'medical-419-S-4-R-0',
              'medical-419-S-4-R-1',
              'medical-419-S-4-R-2',
              'medical-419-S-4-R-3',
              'medical-419-S-4-R-4',
              'medical-419-S-4-R-5',
              'medical-419-S-4-R-8',
              'medical-420-S-1',
              'medical-420-S-1-R-0',
              'medical-420-S-1-R-1',
              'medical-420-S-1-R-2',
              'medical-420-S-1-R-4',
              'medical-420-S-1-R-5',
              'medical-420-S-1-R-6',
              'medical-428-S-3-R-5',
              'medical-428-S-3-R-6',
              'medical-428-S-3-R-7',
              'medical-482-S-2-R-5',
              'medical-482-S-2-R-7',
              'medical-501-S-5-R-6',
              'medical-510-S-2-R-1',
              'medical-511-S-0-R-1',
              'medical-515-S-2',
              'medical-515-S-2-R-0',
              'medical-515-S-2-R-1',
              'medical-515-S-2-R-4',
              'medical-518-S-0-R-0',
              'medical-518-S-0-R-1',
              'medical-518-S-0-R-9',
              'medical-518-S-3-R-0',
              'medical-518-S-3-R-1',
              'medical-519-S-0-R-1',
              'medical-519-S-1',
              'medical-519-S-1-R-1',
              'medical-519-S-1-R-2',
              'medical-519-S-1-R-3',
              'medical-519-S-1-R-4',
              'medical-519-S-1-R-5',
              'medical-519-S-1-R-6',
              'medical-519-S-1-R-7',
              'medical-519-S-1-R-8',
              'medical-519-S-1-R-9',
              'medical-519-S-1-R-10',
              'medical-519-S-1-R-11',
              'medical-519-S-1-R-12',
              'medical-519-S-1-R-13',
              'medical-519-S-1-R-14',
              'medical-519-S-2',
              'medical-519-S-2-R-0',
              'medical-519-S-2-R-1',
              'medical-519-S-2-R-2',
              'medical-519-S-2-R-3',
              'medical-519-S-2-R-4',
              'medical-519-S-2-R-5',
              'medical-519-S-2-R-6',
              'medical-519-S-2-R-7',
              'medical-519-S-2-R-8',
              'medical-519-S-2-R-9',
              'medical-520-S-0',
              'medical-520-S-0-R-3',
              'medical-520-S-0-R-5',
              'medical-520-S-0-R-6',
              'medical-520-S-0-R-7',
              'medical-520-S-0-R-8',
              'medical-520-S-0-R-9',
              'medical-520-S-0-R-10',
              'medical-520-S-0-R-11',
              'medical-520-S-0-R-13',
              'medical-520-S-0-R-14',
              'medical-520-S-0-R-15',
              'medical-520-S-0-R-16',
              'medical-520-S-0-R-18',
              'medical-520-S-0-R-19',
              'medical-520-S-0-R-20',
              'medical-520-S-0-R-21',
              'medical-520-S-0-R-22',
              'medical-520-S-0-R-23',
              'medical-520-S-0-R-24',
              'medical-520-S-0-R-25',
              'medical-520-S-0-R-26',
              'medical-520-S-1',
              'medical-520-S-1-R-0',
              'medical-520-S-1-R-1',
              'medical-520-S-1-R-2',
              'medical-520-S-1-R-3',
              'medical-520-S-1-R-4',
              'medical-520-S-1-R-5',
              'medical-520-S-1-R-6',
              'medical-520-S-1-R-7',
              'medical-520-S-1-R-8',
              'medical-521-S-1-R-9',
              'medical-521-S-2-R-1',
              'medical-521-S-2-R-2',
              'medical-521-S-3-R-0',
              'medical-523-S-1-R-1',
              'medical-523-S-1-R-5',
              'medical-523-S-1-R-6',
              'medical-524-S-3',
              'medical-524-S-3-R-0',
              'medical-524-S-4',
              'medical-524-S-4-R-0',
              'medical-524-S-4-R-1',
              'medical-524-S-4-R-2',
              'medical-524-S-4-R-3',
              'medical-524-S-4-R-4',
              'medical-524-S-4-R-5',
              'medical-524-S-4-R-6',
              'medical-524-S-4-R-7',
              'medical-525-S-0-R-1',
              'medical-525-S-2',
              'medical-525-S-2-R-0',
              'medical-525-S-2-R-3',
              'medical-525-S-2-R-4',
              'medical-525-S-2-R-5',
              'medical-525-S-2-R-6',
              'medical-525-S-2-R-7',
              'medical-525-S-2-R-8',
              'medical-525-S-2-R-9',
              'medical-525-S-2-R-10',
              'medical-525-S-2-R-11',
              'medical-525-S-2-R-12',
              'medical-525-S-3',
              'medical-525-S-3-R-0',
              'medical-525-S-3-R-2',
              'medical-525-S-3-R-3',
              'medical-525-S-4',
              'medical-525-S-4-R-0',
              'medical-525-S-4-R-1',
              'medical-525-S-4-R-2',
              'medical-525-S-4-R-3',
              'medical-525-S-4-R-4',
              'medical-525-S-4-R-5',
              'medical-525-S-5-R-0',
              'medical-525-S-6',
              'medical-526-S-4',
              'medical-526-S-4-R-2',
              'medical-526-S-4-R-3',
              'medical-527-S-5-R-3',
              'medical-527-S-5-R-4',
              'medical-527-S-6',
              'medical-527-S-6-R-0',
              'medical-527-S-7',
              'medical-527-S-7-R-0',
              'medical-527-S-7-R-1',
              'medical-527-S-7-R-2',
              'medical-527-S-7-R-3',
              'medical-527-S-7-R-4',
              'medical-527-S-7-R-5',
              'medical-527-S-7-R-6',
              'medical-527-S-7-R-7',
              'medical-527-S-7-R-8',
              'medical-527-S-7-R-9',
              'medical-527-S-8-R-3',
              'medical-528-S-0',
              'medical-528-S-0-R-0',
              'medical-528-S-0-R-1',
              'medical-528-S-0-R-2',
              'medical-528-S-0-R-3',
              'medical-528-S-0-R-4',
              'medical-528-S-0-R-6',
              'medical-528-S-0-R-7',
              'medical-528-S-1-R-3',
              'medical-529-S-5',
              'medical-529-S-5-R-0',
              'medical-529-S-5-R-1',
              'medical-529-S-5-R-2',
              'medical-529-S-5-R-3',
              'medical-529-S-5-R-4',
              'medical-529-S-5-R-5',
              'medical-530-S-0-R-9',
              'medical-530-S-0-R-10',
              'medical-530-S-0-R-11',
              'medical-530-S-0-R-12',
              'medical-530-S-2-R-1',
              'medical-535-S-0-R-11',
              'medical-536-S-2-R-0',
              'medical-539-S-2',
              'medical-539-S-2-R-0',
              'medical-539-S-2-R-1',
              'medical-539-S-2-R-2',
              'medical-539-S-2-R-3',
              'medical-539-S-2-R-4',
              'medical-539-S-2-R-5',
              'medical-539-S-2-R-6',
              'medical-539-S-2-R-7',
              'medical-539-S-2-R-8',
              'medical-541-S-2',
              'medical-541-S-2-R-0',
              'medical-541-S-2-R-1',
              'medical-541-S-2-R-2',
              'medical-541-S-2-R-3',
              'medical-541-S-2-R-4',
              'medical-541-S-2-R-5',
              'medical-541-S-2-R-6',
              'medical-541-S-2-R-7',
              'medical-541-S-2-R-8',
              'medical-541-S-2-R-9',
              'medical-541-S-3-R-3',
              'medical-542-S-1-R-1',
              'medical-542-S-1-R-2',
              'medical-542-S-1-R-3',
              'medical-542-S-1-R-7',
              'medical-545-S-0-R-0',
              'medical-545-S-0-R-4',
              'medical-545-S-2',
              'medical-545-S-2-R-0',
              'medical-545-S-2-R-1',
              'medical-545-S-2-R-2',
              'medical-545-S-2-R-4',
              'medical-545-S-2-R-5',
              'medical-545-S-2-R-6',
              'medical-545-S-2-R-7',
              'medical-545-S-2-R-8',
              'medical-546-S-0-R-0',
              'medical-546-S-0-R-1',
              'medical-546-S-0-R-2',
              'medical-548-S-3-R-4',
              'medical-550-S-2-R-0',
              'medical-550-S-2-R-1',
              'medical-552-S-1',
              'medical-552-S-1-R-0',
              'medical-552-S-1-R-1',
              'medical-552-S-1-R-2',
              'medical-552-S-1-R-3',
              'medical-552-S-1-R-4',
              'medical-552-S-1-R-5',
              'medical-552-S-1-R-6',
              'medical-552-S-1-R-7',
              'medical-552-S-1-R-8',
              'medical-552-S-1-R-9',
              'medical-552-S-1-R-10',
              'medical-552-S-1-R-11',
              'medical-552-S-1-R-12',
              'medical-552-S-1-R-13',
              'medical-552-S-1-R-14',
              'medical-552-S-1-R-15',
              'medical-552-S-2-R-1',
              'medical-552-S-2-R-2',
              'medical-552-S-2-R-3',
              'medical-552-S-2-R-19',
              'medical-552-S-2-R-27',
              'medical-553-S-3',
              'medical-553-S-3-R-0',
              'medical-553-S-3-R-1',
              'medical-553-S-3-R-2',
              'medical-553-S-3-R-3',
              'medical-N-1',
              'medical-N-2',
              'medical-N-3',
              'medical-N-353',
              'medical-N-372',
              'medical-N-373',
              'medical-N-375',
              'medical-N-378',
              'medical-N-379',
              'medical-N-381',
              'medical-N-382',
              'medical-N-383',
              'medical-N-384',
              'medical-N-730',
              'medical-N-732',
              'medical-N-757',
              'medical-N-799',
              'medical-N-800',
              'medical-N-2244',
              'medical-N-2245',
              'medical-N-2246',
              'medical-N-2626',
              'medical-N-2634',
              'medical-N-2690',
              'medical-N-2692',
              'medical-N-2693',
              'medical-N-2694',
              'medical-N-2695',
              'medical-N-2696',
              'medical-N-2697',
              'medical-N-2698',
              'medical-N-2699',
              'medical-N-2700',
              'medical-N-2702',
              'medical-N-2703',
              'medical-N-2704',
              'medical-N-2705',
              'medical-N-2706',
              'medical-N-2707',
              'medical-N-2708',
              'medical-N-2709',
              'medical-N-2710',
              'medical-N-2711',
              'medical-N-2712',
              'medical-N-2713',
              'medical-N-2714',
              'medical-N-2715',
              'medical-N-2716',
              'medical-N-2718',
              'medical-N-2719',
              'medical-N-2720',
              'medical-N-3943',
              'medical-N-4579',
              'medical-N-4580',
              'medical-N-4581',
              'medical-N-4582',